DATA LIST FILE='C:\COUNTRIES\ZZ62\ZZBR62FL.DAT' RECORDS=1
  /
  CASEID      1-15   (A)
  BIDX       16-17  
  V000       18-20   (A)
  V001       21-28  
  V002       29-32  
  V003       33-35  
  V004       36-39  
  V005       40-47  
  V006       48-49  
  V007       50-53  
  V008       54-57  
  V009       58-59  
  V010       60-63  
  V011       64-67  
  V012       68-69  
  V013       70-70  
  V014       71-71  
  V015       72-72  
  V016       73-74  
  V017       75-78  
  V018       79-80  
  V019       81-82  
  V019A      83-83  
  V020       84-84  
  V021       85-88  
  V022       89-92  
  V023       93-94  
  V024       95-96  
  V025       97-97  
  V026       98-98  
  V027       99-99  
  V028      100-102 
  V029      103-104 
  V030      105-107 
  V031      108-110 
  V032      111-112 
  V034      113-114 
  V040      115-118 
  V042      119-119 
  V044      120-120 
  V101      121-122 
  V102      123-123 
  V103      124-124 
  V104      125-126 
  V105      127-127 
  V106      128-128 
  V107      129-130 
  V113      131-132 
  V115      133-135 
  V116      136-137 
  V119      138-138 
  V120      139-139 
  V121      140-140 
  V122      141-141 
  V123      142-142 
  V124      143-143 
  V125      144-144 
  V127      145-146 
  V128      147-148 
  V129      149-150 
  V130      151-152 
  V131      153-155 
  V133      156-157 
  V134      158-158 
  V135      159-159 
  V136      160-161 
  V137      162-163 
  V138      164-165 
  V139      166-167 
  V140      168-168 
  V141      169-169 
  V149      170-170 
  V150      171-172 
  V151      173-173 
  V152      174-175 
  V153      176-176 
  AWFACTT   177-181 
  AWFACTU   182-186 
  AWFACTR   187-191 
  AWFACTE   192-196 
  AWFACTW   197-201 
  V155      202-202 
  V156      203-203 
  V157      204-204 
  V158      205-205 
  V159      206-206 
  V160      207-207 
  V161      208-209 
  V166      210-212 
  V167      213-214 
  V168      215-215 
  V190      216-216 
  V191      217-224 
  ML101     225-225 
  V201      226-227 
  V202      228-229 
  V203      230-231 
  V204      232-233 
  V205      234-235 
  V206      236-237 
  V207      238-239 
  V208      240-240 
  V209      241-241 
  V210      242-242 
  V211      243-246 
  V212      247-248 
  V213      249-249 
  V214      250-251 
  V215      252-254 
  V216      255-255 
  V217      256-256 
  V218      257-258 
  V219      259-260 
  V220      261-261 
  V221      262-264 
  V222      265-267 
  V223      268-268 
  V224      269-270 
  V225      271-271 
  V226      272-274 
  V227      275-275 
  V228      276-276 
  V229      277-278 
  V230      279-282 
  V231      283-286 
  V232      287-287 
  V233      288-289 
  V234      290-290 
  V235      291-292 
  V237      293-293 
  V238      294-294 
  V239      295-295 
  V240      296-297 
  V241      298-301 
  V242      302-305 
  V243      306-306 
  V310      307-308 
  V311      309-309 
  V312      310-311 
  V313      312-312 
  V315      313-314 
  V316      315-318 
  V317      319-322 
  V318      323-323 
  V319      324-324 
  V320      325-325 
  V321      326-326 
  V322      327-327 
  V323      328-329 
  V323A     330-331 
  V325A     332-338 
  V326      339-340 
  V327      341-341 
  V337      342-344 
  V359      345-346 
  V360      347-348 
  V361      349-349 
  V362      350-350 
  V363      351-352 
  V364      353-353 
  V367      354-354 
  V372      355-355 
  V372A     356-356 
  V375A     357-358 
  V376      359-360 
  V376A     361-361 
  V379      362-363 
  V380      364-364 
  V384A     365-365 
  V384B     366-366 
  V384C     367-367 
  V393      368-368 
  V394      369-369 
  V395      370-370 
  V3A00A    371-371 
  V3A00B    372-372 
  V3A00C    373-373 
  V3A00D    374-374 
  V3A00E    375-375 
  V3A00F    376-376 
  V3A00G    377-377 
  V3A00H    378-378 
  V3A00I    379-379 
  V3A00J    380-380 
  V3A00K    381-381 
  V3A00L    382-382 
  V3A00M    383-383 
  V3A00N    384-384 
  V3A00O    385-385 
  V3A00P    386-386 
  V3A00Q    387-387 
  V3A00R    388-388 
  V3A00S    389-389 
  V3A00T    390-390 
  V3A00U    391-391 
  V3A00V    392-392 
  V3A00W    393-393 
  V3A00X    394-394 
  V3A00Y    395-395 
  V3A00Z    396-396 
  V3A01     397-397 
  V3A02     398-398 
  V3A03     399-399 
  V3A04     400-400 
  V3A05     401-401 
  V3A06     402-402 
  V3A07     403-404 
  V3A08A    405-405 
  V3A08B    406-406 
  V3A08C    407-407 
  V3A08D    408-408 
  V3A08E    409-409 
  V3A08F    410-410 
  V3A08G    411-411 
  V3A08H    412-412 
  V3A08I    413-413 
  V3A08J    414-414 
  V3A08K    415-415 
  V3A08L    416-416 
  V3A08M    417-417 
  V3A08N    418-418 
  V3A08O    419-419 
  V3A08P    420-420 
  V3A08Q    421-421 
  V3A08R    422-422 
  V3A08S    423-423 
  V3A08T    424-424 
  V3A08U    425-425 
  V3A08V    426-426 
  V3A08W    427-427 
  V3A08AA   428-428 
  V3A08AB   429-429 
  V3A08AC   430-430 
  V3A08AD   431-431 
  V3A08X    432-432 
  V3A08Z    433-433 
  V3A09A    434-436 
  V3A09B    437-439 
  V401      440-440 
  V404      441-441 
  V405      442-442 
  V406      443-443 
  V407      444-445 
  V408      446-447 
  V409      448-448 
  V409A     449-449 
  V410      450-450 
  V410A     451-451 
  V411      452-452 
  V411A     453-453 
  V412      454-454 
  V412A     455-455 
  V412B     456-456 
  V412C     457-457 
  V413      458-458 
  V413A     459-459 
  V413B     460-460 
  V413C     461-461 
  V413D     462-462 
  V414A     463-463 
  V414B     464-464 
  V414C     465-465 
  V414D     466-466 
  V414E     467-467 
  V414F     468-468 
  V414G     469-469 
  V414H     470-470 
  V414I     471-471 
  V414J     472-472 
  V414K     473-473 
  V414L     474-474 
  V414M     475-475 
  V414N     476-476 
  V414O     477-477 
  V414P     478-478 
  V414Q     479-479 
  V414R     480-480 
  V414S     481-481 
  V414T     482-482 
  V414U     483-483 
  V414V     484-484 
  V414W     485-485 
  V415      486-486 
  V416      487-487 
  V417      488-488 
  V418      489-489 
  V419      490-490 
  V420      491-493 
  V421      494-496 
  V426      497-499 
  V437      500-503 
  V438      504-507 
  V439      508-511 
  V440      512-515 
  V441      516-520 
  V442      521-525 
  V443      526-530 
  V444      531-535 
  V444A     536-539 
  V445      540-543 
  V446      544-547 
  V447      548-548 
  V447A     549-550 
  V452A     551-551 
  V452B     552-553 
  V452C     554-554 
  V453      555-557 
  V454      558-558 
  V455      559-559 
  V456      560-562 
  V457      563-563 
  V458      564-564 
  V459      565-565 
  V460      566-566 
  V461      567-567 
  V462      568-568 
  V463A     569-569 
  V463B     570-570 
  V463C     571-571 
  V463D     572-572 
  V463E     573-573 
  V463F     574-574 
  V463G     575-575 
  V463X     576-576 
  V463Z     577-577 
  V464      578-579 
  V465      580-581 
  V466      582-582 
  V467A     583-583 
  V467B     584-584 
  V467C     585-585 
  V467D     586-586 
  V467E     587-587 
  V467F     588-588 
  V467G     589-589 
  V467H     590-590 
  V467I     591-591 
  V467J     592-592 
  V467K     593-593 
  V467L     594-594 
  V467M     595-595 
  V468      596-596 
  V469E     597-597 
  V469F     598-598 
  V469X     599-599 
  V471A     600-600 
  V471B     601-601 
  V471C     602-602 
  V471D     603-603 
  V471E     604-604 
  V471F     605-605 
  V471G     606-606 
  V472A     607-607 
  V472B     608-608 
  V472C     609-609 
  V472D     610-610 
  V472E     611-611 
  V472F     612-612 
  V472G     613-613 
  V472H     614-614 
  V472I     615-615 
  V472J     616-616 
  V472K     617-617 
  V472L     618-618 
  V472M     619-619 
  V472N     620-620 
  V472O     621-621 
  V472P     622-622 
  V472Q     623-623 
  V472R     624-624 
  V472S     625-625 
  V472T     626-626 
  V472U     627-627 
  V473A     628-628 
  V473B     629-629 
  V474      630-630 
  V474A     631-631 
  V474B     632-632 
  V474C     633-633 
  V474D     634-634 
  V474E     635-635 
  V474F     636-636 
  V474G     637-637 
  V474H     638-638 
  V474I     639-639 
  V474J     640-640 
  V474X     641-641 
  V474Z     642-642 
  V475      643-643 
  V476      644-644 
  V477      645-646 
  V478      647-648 
  V479      649-650 
  V480      651-651 
  V481      652-652 
  V481A     653-653 
  V481B     654-654 
  V481C     655-655 
  V481D     656-656 
  V481E     657-657 
  V481F     658-658 
  V481G     659-659 
  V481H     660-660 
  V481X     661-661 
  V482A     662-662 
  V482B     663-663 
  V482C     664-664 
  V501      665-665 
  V502      666-666 
  V503      667-667 
  V504      668-668 
  V505      669-670 
  V506      671-672 
  V507      673-674 
  V508      675-678 
  V509      679-682 
  V510      683-683 
  V511      684-685 
  V512      686-687 
  V513      688-688 
  V525      689-690 
  V527      691-693 
  V528      694-695 
  V529      696-698 
  V530      699-699 
  V531      700-701 
  V532      702-702 
  V535      703-703 
  V536      704-704 
  V537      705-706 
  V538      707-707 
  V539      708-708 
  V540      709-709 
  V541      710-710 
  V602      711-711 
  V603      712-714 
  V604      715-715 
  V605      716-716 
  V613      717-718 
  V614      719-719 
  V616      720-722 
  V621      723-723 
  V623      724-724 
  V624      725-726 
  V625      727-727 
  V626      728-729 
  V625A     730-730 
  V626A     731-732 
  V627      733-734 
  V628      735-736 
  V629      737-738 
  V631      739-739 
  V632      740-740 
  V633A     741-741 
  V633B     742-742 
  V633C     743-743 
  V633D     744-744 
  V633E     745-745 
  V633F     746-746 
  V633G     747-747 
  V634      748-748 
  V701      749-749 
  V702      750-751 
  V704      752-754 
  V705      755-756 
  V714      757-757 
  V714A     758-758 
  V715      759-760 
  V716      761-763 
  V717      764-765 
  V719      766-766 
  V721      767-767 
  V729      768-768 
  V730      769-770 
  V731      771-771 
  V732      772-772 
  V739      773-773 
  V740      774-774 
  V741      775-775 
  V743A     776-776 
  V743B     777-777 
  V743C     778-778 
  V743D     779-779 
  V743E     780-780 
  V743F     781-781 
  V744A     782-782 
  V744B     783-783 
  V744C     784-784 
  V744D     785-785 
  V744E     786-786 
  V745A     787-787 
  V745B     788-788 
  V746      789-789 
  BORD      790-791 
  B0        792-792 
  B1        793-794 
  B2        795-798 
  B3        799-802 
  B4        803-803 
  B5        804-804 
  B6        805-807 
  B7        808-810 
  B8        811-812 
  B9        813-813 
  B10       814-814 
  B11       815-817 
  B12       818-820 
  B13       821-821 
  B15       822-822 
  B16       823-824 
  MIDX      825-825 
  M1        826-826 
  M1A       827-827 
  M1B       828-829 
  M1C       830-833 
  M1D       834-835 
  M1E       836-839 
  M2A       840-840 
  M2B       841-841 
  M2C       842-842 
  M2D       843-843 
  M2E       844-844 
  M2F       845-845 
  M2G       846-846 
  M2H       847-847 
  M2I       848-848 
  M2J       849-849 
  M2K       850-850 
  M2L       851-851 
  M2M       852-852 
  M2N       853-853 
  M3A       854-854 
  M3B       855-855 
  M3C       856-856 
  M3D       857-857 
  M3E       858-858 
  M3F       859-859 
  M3G       860-860 
  M3H       861-861 
  M3I       862-862 
  M3J       863-863 
  M3K       864-864 
  M3L       865-865 
  M3M       866-866 
  M3N       867-867 
  M4        868-869 
  M5        870-871 
  M6        872-873 
  M7        874-875 
  M8        876-877 
  M9        878-879 
  M10       880-880 
  M11       881-883 
  M13       884-885 
  M14       886-887 
  M15       888-889 
  M17       890-890 
  M18       891-891 
  M19       892-895 
  M19A      896-896 
  M27       897-897 
  M28       898-898 
  M29       899-899 
  M34       900-902 
  M35       903-904 
  M36       905-906 
  M38       907-907 
  M39A      908-908 
  M39       909-909 
  M42A      910-910 
  M42B      911-911 
  M42C      912-912 
  M42D      913-913 
  M42E      914-914 
  M43       915-915 
  M44       916-916 
  M45       917-917 
  M46       918-920 
  M47       921-921 
  M48       922-922 
  M49A      923-923 
  M49B      924-924 
  M49C      925-925 
  M49D      926-926 
  M49E      927-927 
  M49F      928-928 
  M49G      929-929 
  M49X      930-930 
  M49Z      931-931 
  M49Y      932-932 
  M50       933-933 
  M51       934-936 
  M52       937-938 
  M54       939-939 
  M55A      940-940 
  M55B      941-941 
  M55C      942-942 
  M55D      943-943 
  M55E      944-944 
  M55F      945-945 
  M55G      946-946 
  M55H      947-947 
  M55I      948-948 
  M55J      949-949 
  M55K      950-950 
  M55L      951-951 
  M55M      952-952 
  M55N      953-953 
  M55O      954-954 
  M55X      955-955 
  M55Z      956-956 
  M57A      957-957 
  M57B      958-958 
  M57C      959-959 
  M57D      960-960 
  M57E      961-961 
  M57F      962-962 
  M57G      963-963 
  M57H      964-964 
  M57I      965-965 
  M57J      966-966 
  M57K      967-967 
  M57L      968-968 
  M57M      969-969 
  M57N      970-970 
  M57O      971-971 
  M57P      972-972 
  M57Q      973-973 
  M57R      974-974 
  M57S      975-975 
  M57T      976-976 
  M57U      977-977 
  M57V      978-978 
  M57X      979-979 
  M60       980-980 
  M61       981-983 
  M62       984-984 
  M65A      985-985 
  M65B      986-986 
  M65C      987-987 
  M65D      988-988 
  M65E      989-989 
  M65F      990-990 
  M65G      991-991 
  M65H      992-992 
  M65I      993-993 
  M65J      994-994 
  M65K      995-995 
  M65L      996-996 
  M65X      997-997 
  M66       998-998 
  M70       999-999 
  M71      1000-1002
  M72      1003-1004
  M73      1005-1006
  HIDX     1007-1007
  H1       1008-1008
  H2       1009-1009
  H2D      1010-1011
  H2M      1012-1013
  H2Y      1014-1017
  H3       1018-1018
  H3D      1019-1020
  H3M      1021-1022
  H3Y      1023-1026
  H4       1027-1027
  H4D      1028-1029
  H4M      1030-1031
  H4Y      1032-1035
  H5       1036-1036
  H5D      1037-1038
  H5M      1039-1040
  H5Y      1041-1044
  H6       1045-1045
  H6D      1046-1047
  H6M      1048-1049
  H6Y      1050-1053
  H7       1054-1054
  H7D      1055-1056
  H7M      1057-1058
  H7Y      1059-1062
  H8       1063-1063
  H8D      1064-1065
  H8M      1066-1067
  H8Y      1068-1071
  H9       1072-1072
  H9D      1073-1074
  H9M      1075-1076
  H9Y      1077-1080
  H0       1081-1081
  H0D      1082-1083
  H0M      1084-1085
  H0Y      1086-1089
  H10      1090-1090
  H11      1091-1091
  H11B     1092-1092
  H12A     1093-1093
  H12B     1094-1094
  H12C     1095-1095
  H12D     1096-1096
  H12E     1097-1097
  H12F     1098-1098
  H12G     1099-1099
  H12H     1100-1100
  H12I     1101-1101
  H12J     1102-1102
  H12K     1103-1103
  H12L     1104-1104
  H12M     1105-1105
  H12N     1106-1106
  H12O     1107-1107
  H12P     1108-1108
  H12Q     1109-1109
  H12R     1110-1110
  H12S     1111-1111
  H12T     1112-1112
  H12U     1113-1113
  H12V     1114-1114
  H12W     1115-1115
  H12X     1116-1116
  H12Y     1117-1117
  H12Z     1118-1118
  H13      1119-1119
  H13B     1120-1120
  H14      1121-1121
  H15      1122-1122
  H15A     1123-1123
  H15B     1124-1124
  H15C     1125-1125
  H15D     1126-1126
  H15E     1127-1127
  H15F     1128-1128
  H15G     1129-1129
  H15H     1130-1130
  H15I     1131-1131
  H15J     1132-1132
  H15K     1133-1133
  H15L     1134-1134
  H15M     1135-1135
  H20      1136-1136
  H21A     1137-1137
  H21      1138-1138
  H22      1139-1139
  H31      1140-1140
  H31B     1141-1141
  H31C     1142-1142
  H31D     1143-1143
  H31E     1144-1144
  H32A     1145-1145
  H32B     1146-1146
  H32C     1147-1147
  H32D     1148-1148
  H32E     1149-1149
  H32F     1150-1150
  H32G     1151-1151
  H32H     1152-1152
  H32I     1153-1153
  H32J     1154-1154
  H32K     1155-1155
  H32L     1156-1156
  H32M     1157-1157
  H32N     1158-1158
  H32O     1159-1159
  H32P     1160-1160
  H32Q     1161-1161
  H32R     1162-1162
  H32S     1163-1163
  H32T     1164-1164
  H32U     1165-1165
  H32V     1166-1166
  H32W     1167-1167
  H32X     1168-1168
  H32Y     1169-1169
  H32Z     1170-1170
  H33      1171-1171
  H33D     1172-1173
  H33M     1174-1175
  H33Y     1176-1179
  H34      1180-1180
  H35      1181-1181
  H36A     1182-1182
  H36B     1183-1183
  H36C     1184-1184
  H36D     1185-1185
  H36E     1186-1186
  H36F     1187-1187
  H37A     1188-1188
  H37B     1189-1189
  H37C     1190-1190
  H37D     1191-1191
  H37E     1192-1192
  H37F     1193-1193
  H37G     1194-1194
  H37H     1195-1195
  H37I     1196-1196
  H37J     1197-1197
  H37K     1198-1198
  H37L     1199-1199
  H37M     1200-1200
  H37N     1201-1201
  H37O     1202-1202
  H37P     1203-1203
  H37X     1204-1204
  H37Y     1205-1205
  H37Z     1206-1206
  H38      1207-1207
  H39      1208-1208
  H40      1209-1209
  H40D     1210-1211
  H40M     1212-1213
  H40Y     1214-1217
  H41A     1218-1218
  H41B     1219-1219
  H42      1220-1220
  H43      1221-1221
  H44A     1222-1223
  H44B     1224-1225
  H44C     1226-1226
  H45      1227-1228
  H46A     1229-1230
  H46B     1231-1232
  H47      1233-1233
  HWIDX    1234-1234
  HW1      1235-1236
  HW2      1237-1240
  HW3      1241-1244
  HW4      1245-1248
  HW5      1249-1252
  HW6      1253-1257
  HW7      1258-1261
  HW8      1262-1265
  HW9      1266-1270
  HW10     1271-1274
  HW11     1275-1278
  HW12     1279-1283
  HW13     1284-1284
  HW15     1285-1285
  HW16     1286-1287
  HW17     1288-1289
  HW18     1290-1291
  HW19     1292-1295
  HW51     1296-1297
  HW52     1298-1298
  HW53     1299-1301
  HW55     1302-1302
  HW56     1303-1306
  HW57     1307-1307
  HW58     1308-1308
  HW70     1309-1312
  HW71     1313-1316
  HW72     1317-1320
  HW73     1321-1324
  IDXML    1325-1325
  ML0      1326-1326
  ML1      1327-1328
  ML2      1329-1329
  ML11     1330-1330
  ML12     1331-1331
  ML13A    1332-1332
  ML13B    1333-1333
  ML13C    1334-1334
  ML13D    1335-1335
  ML13E    1336-1336
  ML13F    1337-1337
  ML13G    1338-1338
  ML13H    1339-1339
  ML13I    1340-1340
  ML13J    1341-1341
  ML13K    1342-1342
  ML13L    1343-1343
  ML13M    1344-1344
  ML13N    1345-1345
  ML13O    1346-1346
  ML13P    1347-1347
  ML13X    1348-1348
  ML13Y    1349-1349
  ML13Z    1350-1350
  ML14A    1351-1351
  ML14B    1352-1352
  ML14Y    1353-1353
  ML14Z    1354-1354
  ML15A    1355-1355
  ML15B    1356-1356
  ML15C    1357-1357
  ML16A    1358-1358
  ML16B    1359-1359
  ML16C    1360-1360
  ML17A    1361-1361
  ML17B    1362-1362
  ML17C    1363-1363
  ML18A    1364-1364
  ML18B    1365-1365
  ML18C    1366-1366
  ML19A    1367-1367
  ML19B    1368-1368
  ML19C    1369-1369
  ML19D    1370-1370
  ML19E    1371-1371
  ML19F    1372-1372
  ML19X    1373-1373
  ML19Y    1374-1374
  ML19Z    1375-1375
  ML20A    1376-1376
  ML20B    1377-1377
  ML20C    1378-1378
  ML21A    1379-1379
  ML21B    1380-1380
  ML21C    1381-1381
  ML22A    1382-1382
  ML22B    1383-1383
  ML22C    1384-1384
  ML23A    1385-1385
  ML23B    1386-1386
  ML23C    1387-1387
  ML24C    1388-1388
  G100     1389-1389
  G101     1390-1390
  G102     1391-1391
  G103     1392-1392
  G104     1393-1393
  G105     1394-1394
  G106     1395-1396
  G107     1397-1398
  G108     1399-1400
  G109     1401-1402
  G110     1403-1403
  G111     1404-1404
  G112     1405-1405
  G113     1406-1407
  G114     1408-1409
  G115     1410-1410
  G116     1411-1411
  G117A    1412-1412
  G117B    1413-1413
  G117C    1414-1414
  G117D    1415-1415
  G117E    1416-1416
  G117F    1417-1417
  G117G    1418-1418
  G117H    1419-1419
  G117I    1420-1420
  G117J    1421-1421
  G117X    1422-1422
  G117Y    1423-1423
  G118     1424-1424
  G119     1425-1425
  SZONE    1426-1426
  SHREG    1427-1427
  IDX94    1428-1428
  S426     1429-1429
  IDX95    1430-1430
  SYF      1431-1431
  SYFD     1432-1433
  SYFM     1434-1435
  SYFY     1436-1439
  SPC1     1440-1440
  SPC1D    1441-1442
  SPC1M    1443-1444
  SPC1Y    1445-1448
  SPC2     1449-1449
  SPC2D    1450-1451
  SPC2M    1452-1453
  SPC2Y    1454-1457
  SPC3     1458-1458
  SPC3D    1459-1460
  SPC3M    1461-1462
  SPC3Y    1463-1466
  SHP0     1467-1467
  SHB0D    1468-1469
  SHB0M    1470-1471
  SHB0Y    1472-1475
 .
VARIABLE LABELS
   CASEID   "Case Identification"
  /BIDX     "Birth column number"
  /V000     "Country code and phase"
  /V001     "Cluster number"
  /V002     "Household number"
  /V003     "Respondent's line number"
  /V004     "Ultimate area unit"
  /V005     "Women's individual sample weight (6 decimals)"
  /V006     "Month of interview"
  /V007     "Year of interview"
  /V008     "Date of interview (CMC)"
  /V009     "Respondent's month of birth"
  /V010     "Respondent's year of birth"
  /V011     "Date of birth (CMC)"
  /V012     "Respondent's current age"
  /V013     "Age in 5-year groups"
  /V014     "Completeness of age information"
  /V015     "Result of individual interview"
  /V016     "Day of interview"
  /V017     "CMC start of calendar"
  /V018     "Row of month of interview"
  /V019     "Length of calendar"
  /V019A    "Number of calendar columns"
  /V020     "Ever-married sample"
  /V021     "Primary sampling unit"
  /V022     "Sample strata for sampling errors"
  /V023     "Stratification used in sample design"
  /V024     "Region"
  /V025     "Type of place of residence"
  /V026     "NA - De facto place of residence"
  /V027     "Number of visits"
  /V028     "Interviewer identification"
  /V029     "Keyer identification"
  /V030     "Field supervisor"
  /V031     "Field editor"
  /V032     "Office editor"
  /V034     "Line number of husband"
  /V040     "NA - Cluster altitude in meters"
  /V042     "Household selected for hemoglobin"
  /V044     "Selected for Domestic Violence module"
  /V101     "Region"
  /V102     "Type of place of residence"
  /V103     "NA - Childhood place of residence"
  /V104     "NA - Years lived in place of residence"
  /V105     "NA - Type of place of previous residence"
  /V106     "Highest educational level"
  /V107     "Highest year of education"
  /V113     "Source of drinking water"
  /V115     "Time to get to water source"
  /V116     "Type of toilet facility"
  /V119     "Household has: electricity"
  /V120     "Household has: radio"
  /V121     "Household has: television"
  /V122     "Household has: refrigerator"
  /V123     "Household has: bicycle"
  /V124     "Household has: motorcycle/scooter"
  /V125     "Household has: car/truck"
  /V127     "Main floor material"
  /V128     "Main wall material"
  /V129     "Main roof material"
  /V130     "Religion"
  /V131     "Ethnicity"
  /V133     "Education in single years"
  /V134     "NA - De facto place of residence"
  /V135     "Usual resident or visitor"
  /V136     "Number of household members (listed)"
  /V137     "Number of children 5 and under in household (de jure)"
  /V138     "Number of eligible women in household (de facto)"
  /V139     "De jure region of residence"
  /V140     "De jure type of place of residence"
  /V141     "NA - De jure place of residence"
  /V149     "Educational attainment"
  /V150     "Relationship to household head"
  /V151     "Sex of household head"
  /V152     "Age of household head"
  /V153     "Household has: telephone (land-line)"
  /AWFACTT  "All woman factor - total"
  /AWFACTU  "All woman factor - urban/rural"
  /AWFACTR  "All woman factor - regional"
  /AWFACTE  "All woman factor - educational"
  /AWFACTW  "All woman factor - wealth index"
  /V155     "Literacy"
  /V156     "NA - Ever participated in a literacy program outside of primary"
  /V157     "Frequency of reading newspaper or magazine"
  /V158     "Frequency of listening to radio"
  /V159     "Frequency of watching television"
  /V160     "Toilet facilities shared with other households"
  /V161     "Type of cooking fuel"
  /V166     "NA - Result of salt test for iodine"
  /V167     "Number of trips in last 12 months"
  /V168     "Away for more than one month in last 12 months"
  /V190     "Wealth index"
  /V191     "Wealth index factor score (5 decimals)"
  /ML101    "Type of mosquito bed net(s) slept under last night"
  /V201     "Total children ever born"
  /V202     "Sons at home"
  /V203     "Daughters at home"
  /V204     "Sons elsewhere"
  /V205     "Daughters elsewhere"
  /V206     "Sons who have died"
  /V207     "Daughters who have died"
  /V208     "Births in last five years"
  /V209     "Births in past year"
  /V210     "Births in month of interview"
  /V211     "Date of first birth (CMC)"
  /V212     "Age of respondent at 1st birth"
  /V213     "Currently pregnant"
  /V214     "Duration of current pregnancy"
  /V215     "Time since last menstrual period"
  /V216     "Menstruated in last six weeks"
  /V217     "Knowledge of ovulatory cycle"
  /V218     "Number of living children"
  /V219     "Living children + current pregnancy"
  /V220     "Living children + current pregnancy (grouped)"
  /V221     "Marriage to first birth interval (months)"
  /V222     "Last birth to interview (months)"
  /V223     "Completeness of current pregnancy information"
  /V224     "Entries in birth history"
  /V225     "Current pregnancy wanted"
  /V226     "Time since last period (comp) (months)"
  /V227     "Flag for last period"
  /V228     "Ever had a terminated pregnancy"
  /V229     "Month pregnancy ended"
  /V230     "Year pregnancy ended"
  /V231     "CMC pregnancy ended"
  /V232     "Completeness of last termination information"
  /V233     "Months when pregnancy ended"
  /V234     "Other such pregnancies"
  /V235     "Index last child prior to maternity-health (calendar)"
  /V237     "Birth between last and interview"
  /V238     "Births in last three years"
  /V239     "Pregnancies terminated before calendar beginning"
  /V240     "Month of last termination prior to calendar"
  /V241     "Year of last termination prior to calendar"
  /V242     "CMC termination ended prior to calendar"
  /V243     "Completeness of last termination date prior to calendar"
  /V310     "NA - Living children at first use"
  /V311     "NA - Children at first use (grouped)"
  /V312     "Current contraceptive method"
  /V313     "Current use by method type"
  /V315     "Month of start of use of method"
  /V316     "Year of start of use of method"
  /V317     "Date of start of use of method (CMC)"
  /V318     "Completeness of information"
  /V319     "Years since sterilization"
  /V320     "Age at sterilization"
  /V321     "Marital duration at sterilization"
  /V322     "Parity at sterilization"
  /V323     "Brand of pill used"
  /V323A    "Brand of condom used"
  /V325A    "NA - Cost of current method (in CURRENCY)"
  /V326     "Last source for current users"
  /V327     "Last source for users by type"
  /V337     "Months of use of current method"
  /V359     "Last method discontinued in last 5 years"
  /V360     "Reason of last discontinuation"
  /V361     "Pattern of use"
  /V362     "Intention to use"
  /V363     "NA - Preferred future method"
  /V364     "Contraceptive use and intention"
  /V367     "Wanted last child"
  /V372     "NA - Shown pill package"
  /V372A    "NA - Shown condom package"
  /V375A    "NA - Main reason not using a method"
  /V376     "NA - Main reason not to use a method"
  /V376A    "NA - Would ever use method if married"
  /V379     "NA - Source known for any method"
  /V380     "NA - Source known for any method"
  /V384A    "Heard family planning on radio last few months"
  /V384B    "Heard family planning on TV last few months"
  /V384C    "Heard family planning in newspaper/magazine last few months"
  /V393     "Visited by family planning worker last 12 months"
  /V394     "Visited health facility last 12 months"
  /V395     "At health facility, told of family planning"
  /V3A00A   "Source of family planning for non-users: government hospital"
  /V3A00B   "Source of family planning for non-users: government health center"
  /V3A00C   "Source of family planning for non-users: family planning clinic"
  /V3A00D   "Source of family planning for non-users: public mobile clinic"
  /V3A00E   "Source of family planning for non-users: public health worker"
  /V3A00F   "Source of family planning for non-users: Other public"
  /V3A00G   "NA - Source of family planning for non-users: CS public sector"
  /V3A00H   "NA - Source of family planning for non-users: CS public sector"
  /V3A00I   "NA - Source of family planning for non-users: CS public sector"
  /V3A00J   "Source of family planning for non-users: private hospital/clinic"
  /V3A00K   "Source of family planning for non-users: pharmacy"
  /V3A00L   "Source of family planning for non-users: private doctor"
  /V3A00M   "Source of family planning for non-users: private mobile clinic"
  /V3A00N   "Source of family planning for non-users: private health worker"
  /V3A00O   "Source of family planning for non-users: other private"
  /V3A00P   "NA - Source of family planning for non-users: CS private sector"
  /V3A00Q   "NA - Source of family planning for non-users: CS private sector"
  /V3A00R   "NA - Source of family planning for non-users: CS private sector"
  /V3A00S   "Source of family planning for non-users: shop"
  /V3A00T   "Source of family planning for non-users: church"
  /V3A00U   "Source of family planning for non-users: friend/relative"
  /V3A00V   "NA - Source of family planning for non-users: CS other"
  /V3A00W   "NA - Source of family planning for non-users: CS other"
  /V3A00X   "Source of family planning for non-users: other"
  /V3A00Y   "Source of family planning for non-users: no source"
  /V3A00Z   "Source of family planning for non-users: any source"
  /V3A01    "NA - Told sterilization would mean no more children"
  /V3A02    "Told about side effects"
  /V3A03    "Told about side effects by health or family planning worker"
  /V3A04    "Told how to deal with side effects"
  /V3A05    "Told about other family planning methods"
  /V3A06    "Told about other family planning methods by health or family planning worker"
  /V3A07    "First source for current method"
  /V3A08A   "Reason not using: not married"
  /V3A08B   "Reason not using: not having sex"
  /V3A08C   "Reason not using: infrequent sex"
  /V3A08D   "Reason not using: menopausal/hysterectomy"
  /V3A08E   "Reason not using: subfecund/infecund"
  /V3A08F   "Reason not using: postpartum amenorrheic"
  /V3A08G   "Reason not using: breastfeeding"
  /V3A08H   "Reason not using: fatalistic"
  /V3A08I   "Reason not using: respondent opposed"
  /V3A08J   "Reason not using: husband/partner opposed"
  /V3A08K   "Reason not using: others opposed"
  /V3A08L   "Reason not using: religious prohibition"
  /V3A08M   "Reason not using: knows no method"
  /V3A08N   "Reason not using: knows no source"
  /V3A08O   "NA - Reason not using: health concerns"
  /V3A08P   "Reason not using: fear of side effects/health concerns"
  /V3A08Q   "Reason not using: lack of access/too far"
  /V3A08R   "Reason not using: costs too much"
  /V3A08S   "Reason not using: inconvenient to use"
  /V3A08T   "Reason not using: interferes with body’s processes"
  /V3A08U   "Reason not using: preferred method not available"
  /V3A08V   "Reason not using: no method available"
  /V3A08W   "NA - Reason not using: CS"
  /V3A08AA  "NA - Reason not using: CS"
  /V3A08AB  "NA - Reason not using: CS"
  /V3A08AC  "NA - Reason not using: CS"
  /V3A08AD  "NA - Reason not using: CS"
  /V3A08X   "Reason not using: other"
  /V3A08Z   "Reason not using: don't know"
  /V3A09A   "NA - How many pill cycles did get last time"
  /V3A09B   "NA - How many condoms did get last time"
  /V401     "Last birth a caesarean section"
  /V404     "Currently breastfeeding"
  /V405     "Currently amenorrheic"
  /V406     "Currently abstaining"
  /V407     "NA - Number of times breastfed during night"
  /V408     "NA - Number of times breastfed during day"
  /V409     "Gave child plain water"
  /V409A    "NA - Gave child sugar water"
  /V410     "Gave child juice"
  /V410A    "NA - Gave child tea or coffee"
  /V411     "Gave child tinned, powdered or fresh milk"
  /V411A    "Gave child baby formula"
  /V412     "NA - Gave child fresh milk"
  /V412A    "Gave child fortified baby food (cerelac, etc)"
  /V412B    "NA - Gave child other porridge/gruel"
  /V412C    "Gave child soup/clear broth"
  /V413     "Gave child other liquid"
  /V413A    "NA - Gave child CS liquid"
  /V413B    "NA - Gave child CS liquid"
  /V413C    "NA - Gave child CS liquid"
  /V413D    "NA - Gave child CS liquid"
  /V414A    "NA - Gave child CS foods"
  /V414B    "NA - Gave child CS foods"
  /V414C    "NA - Gave child CS foods"
  /V414D    "NA - Gave child CS foods"
  /V414E    "Gave child bread, noodles, other made from grains"
  /V414F    "Gave child potatoes, cassava, or other tubers"
  /V414G    "Gave child eggs"
  /V414H    "Gave child meat (beef, pork, lamb, chicken, etc)"
  /V414I    "Gave child pumpkin, carrots, squash (yellow or orange inside)"
  /V414J    "Gave child any dark green leafy vegetables"
  /V414K    "Gave child mangoes, papayas, other vitamin A fruits"
  /V414L    "Gave child any other fruits"
  /V414M    "Gave child liver, heart, other organs"
  /V414N    "Gave child fish or shellfish"
  /V414O    "Gave child food made from beans, peas, lentils, nuts"
  /V414P    "Gave child cheese, yogurt, other milk products"
  /V414Q    "NA - Gave child oil, fats, butter, products made of them"
  /V414R    "NA - Gave child chocolates, sweets, candies, pastries, etc"
  /V414S    "Gave child other solid-semisolid food"
  /V414T    "NA - Gave child CS foods"
  /V414U    "NA - Gave child CS foods"
  /V414V    "Gave child yogurt"
  /V414W    "NA - Gave child CS foods"
  /V415     "Drank from bottle with nipple yesterday/last night"
  /V416     "Heard of oral rehydration"
  /V417     "Entries in maternity table"
  /V418     "Entries in health table"
  /V419     "Entries in height/weight table"
  /V420     "NA - Measurer's code"
  /V421     "NA - Assistant measurer's code"
  /V426     "When child put to breast"
  /V437     "Respondent's weight in kilograms (1 decimal)"
  /V438     "Respondent's height in centimeters (1 decimal)"
  /V439     "Height/Age percentile"
  /V440     "Height/Age standard deviation"
  /V441     "Height/Age percent ref. median"
  /V442     "Weight/Height percent ref. median (DHS)"
  /V443     "Weight/Height percent ref. median (Fog)"
  /V444     "Weight/Height percent ref. median (WHO)"
  /V444A    "Weight/Height standard deviation (DHS)"
  /V445     "Body Mass Index"
  /V446     "Rohrer's index"
  /V447     "Result of measurement - height/weight"
  /V447A    "Women's age in years (from household questionnaire)"
  /V452A    "Under age 18 (from household questionnaire)"
  /V452B    "Line number of parent/caretaker"
  /V452C    "Read consent statement - hemoglobin"
  /V453     "Hemoglobin level (g/dl - 1 decimal)"
  /V454     "Currently pregnant (from household questionnaire)"
  /V455     "Result of measurement - hemoglobin"
  /V456     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
  /V457     "Anemia level"
  /V458     "NA - Agrees to referral - anemia"
  /V459     "Have mosquito bed net for sleeping (from household questionnaire)"
  /V460     "Children under 5 slept under mosquito bed net last night (household questionnaire)"
  /V461     "Respondent slept under mosquito bed net"
  /V462     "NA - Washed hands before preparing last meal"
  /V463A    "Smokes cigarettes"
  /V463B    "Smokes pipe"
  /V463C    "Uses chewing tobacco"
  /V463D    "Uses snuff"
  /V463E    "NA - Smokes cigars"
  /V463F    "NA - Smokes country specific"
  /V463G    "NA - Smokes country specific"
  /V463X    "Smokes other"
  /V463Z    "Does not use tobacco"
  /V464     "Number of cigarettes in last 24 hours"
  /V465     "Disposal of youngest child's stools when not using toilet"
  /V466     "NA - When child is seriously ill, can decide whether medical treatment sought"
  /V467A    "NA - Getting medical help for self: know where to go"
  /V467B    "Getting medical help for self: getting permission to go"
  /V467C    "Getting medical help for self: getting money needed for treatment"
  /V467D    "Getting medical help for self: distance to health facility"
  /V467E    "NA - Getting medical help for self: having to take transport"
  /V467F    "Getting medical help for self: not wanting to go alone"
  /V467G    "NA - Getting medical help for self: concern no female health provider"
  /V467H    "NA - Getting medical help for self: concern no provider"
  /V467I    "NA - Getting medical help for self: concern no drugs available"
  /V467J    "NA - Getting medical help for self: CS"
  /V467K    "NA - Getting medical help for self: CS"
  /V467L    "NA - Getting medical help for self: CS"
  /V467M    "NA - Getting medical help for self: CS"
  /V468     "Record for Last Birth"
  /V469E    "Times gave child powdered/tinned/fresh milk"
  /V469F    "Times gave child infant formula"
  /V469X    "Times gave child yogurt"
  /V471A    "NA - Mother had tinned, powdered or fresh milk"
  /V471B    "NA - Mother had tea or coffee"
  /V471C    "NA - Mother had any other liquid"
  /V471D    "NA - Mother had CS liquid"
  /V471E    "NA - Mother had CS liquid"
  /V471F    "NA - Mother had CS liquid"
  /V471G    "NA - Mother had CS liquid"
  /V472A    "NA - Mother had CS foods"
  /V472B    "NA - Mother had CS foods"
  /V472C    "NA - Mother had CS foods"
  /V472D    "NA - Mother had CS foods"
  /V472E    "NA - Mother had bread, noodles, other made from grains"
  /V472F    "NA - Mother had potatoes, cassava, or other tubers"
  /V472G    "NA - Mother had eggs"
  /V472H    "NA - Mother had meat (beef, pork, lamb, chicken, etc)"
  /V472I    "NA - Mother had pumpkin, carrots, squash (yellow or orange inside)"
  /V472J    "NA - Mother had any dark green leafy vegetables"
  /V472K    "NA - Mother had mangoes, papayas, other vitamin A fruits"
  /V472L    "NA - Mother had any other fruits"
  /V472M    "NA - Mother had liver, heart, other organs"
  /V472N    "NA - Mother had fish or shellfish"
  /V472O    "NA - Mother had food made from beans, peas, lentils, nuts"
  /V472P    "NA - Mother had cheese, yogurt, other milk products"
  /V472Q    "NA - Mother had oil, fats, butter, products made of them"
  /V472R    "NA - Mother had chocolates, sweets, candies, pastries, etc"
  /V472S    "NA - Mother had other solid-semisolid food"
  /V472T    "NA - Mother had CS foods"
  /V472U    "NA - Mother had CS foods"
  /V473A    "Read consent statement - HIV"
  /V473B    "Result of measurement - HIV"
  /V474     "NA - Heard of tuberculosis or TB"
  /V474A    "NA - Tuberculosis spread by: air when coughing or sneezing"
  /V474B    "NA - Tuberculosis spread by: sharing utensils"
  /V474C    "NA - Tuberculosis spread by: touching a person with TB"
  /V474D    "NA - Tuberculosis spread by: food"
  /V474E    "NA - Tuberculosis spread by: sexual contact"
  /V474F    "NA - Tuberculosis spread by: mosquito bites"
  /V474G    "NA - Tuberculosis spread by: CS"
  /V474H    "NA - Tuberculosis spread by: CS"
  /V474I    "NA - Tuberculosis spread by: CS"
  /V474J    "NA - Tuberculosis spread by: CS"
  /V474X    "NA - Tuberculosis spread by: other"
  /V474Z    "NA - Tuberculosis spread by: don't know"
  /V475     "NA - Tuberculosis can be cured"
  /V476     "NA - Keep secret when family member gets TB"
  /V477     "Number of injections in last 12 months"
  /V478     "Number of injections administered by a health worker"
  /V479     "NA - Place of injection by health worker"
  /V480     "Syringe and needle from new, unopened package"
  /V481     "Covered by health insurance"
  /V481A    "Health insurance type: mutual/community organization"
  /V481B    "Health insurance type: provided by employer"
  /V481C    "Health insurance type: social security"
  /V481D    "Health insurance type: private/commercially purchased"
  /V481E    "NA - Health insurance type: CS"
  /V481F    "NA - Health insurance type: CS"
  /V481G    "NA - Health insurance type: CS"
  /V481H    "NA - Health insurance type: CS"
  /V481X    "Health insurance type: other"
  /V482A    "NA - Arrange care of biological children under age 18"
  /V482B    "NA - Primary caregiver of children under age 18"
  /V482C    "NA - Arrange care of non-biological children < 18"
  /V501     "Current marital status"
  /V502     "Currently/formerly/never in union"
  /V503     "Number of unions"
  /V504     "Currently residing with husband/partner"
  /V505     "Number of other wives"
  /V506     "Respondent's rank among wives"
  /V507     "Month of first cohabitation"
  /V508     "Year of first cohabitation"
  /V509     "Date of first cohabitation (CMC)"
  /V510     "Completeness of date information in V509"
  /V511     "Age at first cohabitation"
  /V512     "Years since first cohabitation"
  /V513     "Cohabitation duration (grouped)"
  /V525     "Age at first sex"
  /V527     "Time since last sex"
  /V528     "Time since last sex (in days)"
  /V529     "Time since last sex (in months)"
  /V530     "Flag for V529"
  /V531     "Age at first sex (imputed)"
  /V532     "Flag for V531"
  /V535     "Ever been married or in union"
  /V536     "Recent sexual activity"
  /V537     "Months of abstinence"
  /V538     "NA - How previous marriage or union ended"
  /V539     "NA - Person who received most of late husband's property"
  /V540     "NA - Respondent received any of late husband's assets or valuables"
  /V541     "NA - Intends to wait until marriage to have sex"
  /V602     "Fertility preference"
  /V603     "Preferred waiting time for birth of a/another child"
  /V604     "Preferred waiting time for birth of a/another child (grouped)"
  /V605     "Desire for more children"
  /V613     "Ideal number of children"
  /V614     "Ideal number of children (grouped)"
  /V616     "Time for future birth"
  /V621     "Husband's desire for children"
  /V623     "Exposure"
  /V624     "Unmet need"
  /V625     "Exposure (definition 2)"
  /V626     "Unmet need (definition 2)"
  /V625A    "Exposure to need for contraception (definition 3)"
  /V626A    "Unmet need for contraception (definition 3)"
  /V627     "Ideal number of boys"
  /V628     "Ideal number of girls"
  /V629     "Ideal number of either sex"
  /V631     "NA - Problem if became pregnant"
  /V632     "Decision maker for using contraception"
  /V633A    "NA - Reason for not having sex: husband has STI"
  /V633B    "Reason for not having sex: husband has other women"
  /V633C    "NA - Reason for not having sex: recent birth"
  /V633D    "NA - Reason for not having sex: tired, not in mood"
  /V633E    "NA - Reason for not having sex: CS"
  /V633F    "NA - Reason for not having sex: CS"
  /V633G    "NA - Reason for not having sex: CS"
  /V634     "NA - Husband knows that respondent is using contraception"
  /V701     "Husband/partner's education level"
  /V702     "Husband/partner's highest year of education (at level in V701)"
  /V704     "Husband/partner's occupation"
  /V705     "Husband/partner's occupation (grouped)"
  /V714     "Respondent currently working"
  /V714A    "Respondent has a job, but currently absent"
  /V715     "Husband/partner's total number of years of education"
  /V716     "Respondent's occupation"
  /V717     "Respondent's occupation (grouped)"
  /V719     "Respondent works for family, others, self"
  /V721     "NA - Respondent works at home or away"
  /V729     "Husband/partner's educational attainment"
  /V730     "Husband/partner's age"
  /V731     "Respondent worked in last 12 months"
  /V732     "Respondent employed all year/seasonal"
  /V739     "Person who usually decides how to spend respondent's earnings"
  /V740     "NA - Type of land where respondent works"
  /V741     "Type of earnings from respondent's work"
  /V743A    "Person who usually decides on respondent's health care"
  /V743B    "Person who usually decides on large household purchases"
  /V743C    "NA - Person who usually decides on household purchases for daily needs"
  /V743D    "Person who usually decides on visits to family or relatives"
  /V743E    "NA - Person who usually decides on food to be cooked each day"
  /V743F    "Person who usually decides what to do with money husband earns"
  /V744A    "Beating justified if wife goes out without telling husband"
  /V744B    "Beating justified if wife neglects the children"
  /V744C    "Beating justified if wife argues with husband"
  /V744D    "Beating justified if wife refuses to have sex with husband"
  /V744E    "Beating justified if wife burns the food"
  /V745A    "Owns a house alone or jointly"
  /V745B    "Owns land alone or jointly"
  /V746     "Respondent earns more than husband/partner"
  /BORD     "Birth order number"
  /B0       "Child is twin"
  /B1       "Month of birth"
  /B2       "Year of birth"
  /B3       "Date of birth (CMC)"
  /B4       "Sex of child"
  /B5       "Child is alive"
  /B6       "Age at death"
  /B7       "Age at death (months, imputed)"
  /B8       "Current age of child"
  /B9       "Child lives with whom"
  /B10      "Completeness of information"
  /B11      "Preceding birth interval (months)"
  /B12      "Succeeding birth interval (months)"
  /B13      "Flag for age at death"
  /B15      "Live birth between births"
  /B16      "Child's line number in household"
  /MIDX     "Index to Birth History"
  /M1       "Number of tetanus injections before birth"
  /M1A      "Number of tetanus injections before pregnancy"
  /M1B      "NA - Month of last tetanus injection before pregnancy"
  /M1C      "NA - Year of last tetanus injection before pregnancy"
  /M1D      "Years ago received last tetanus injection before pregnancy"
  /M1E      "Last tetanus injection before pregnancy (CMC)"
  /M2A      "Prenatal: doctor"
  /M2B      "Prenatal: Nurse midwife"
  /M2C      "Prenatal: Auxiliary midwife"
  /M2D      "NA - Prenatal: CS health professional"
  /M2E      "NA - Prenatal: CS health professional"
  /M2F      "NA - Prenatal: CS health professional"
  /M2G      "Prenatal: traditional birth attendant"
  /M2H      "Prenatal: Community/village health worker"
  /M2I      "NA - Prenatal: CS other person"
  /M2J      "NA - Prenatal: CS other person"
  /M2K      "Prenatal: other"
  /M2L      "NA - Prenatal: CS other"
  /M2M      "NA - Prenatal: CS other"
  /M2N      "Prenatal: no one"
  /M3A      "Assistance: doctor"
  /M3B      "Assistance: Nurse/Midwife"
  /M3C      "Assistance: Auxiliary midwife"
  /M3D      "NA - Assistance: CS health professional"
  /M3E      "NA - Assistance: CS health professional"
  /M3F      "NA - Assistance: CS health professional"
  /M3G      "Assistance: traditional birth attendant"
  /M3H      "Assistance: relative/friend"
  /M3I      "NA - Assistance: CS other person"
  /M3J      "NA - Assistance: CS other person"
  /M3K      "Assistance: other"
  /M3L      "NA - Assistance: CS other"
  /M3M      "NA - Assistance: CS other"
  /M3N      "Assistance: no one"
  /M4       "Duration of breastfeeding"
  /M5       "Months of breastfeeding"
  /M6       "Duration of amenorrhea"
  /M7       "Months of amenorrhea"
  /M8       "Duration of abstinence"
  /M9       "Months of abstinence"
  /M10      "Wanted pregnancy when became pregnant"
  /M11      "Desired time would have waited"
  /M13      "Timing of 1st antenatal check (months)"
  /M14      "Number of antenatal visits during pregnancy"
  /M15      "Place of delivery"
  /M17      "Delivery by caesarean section"
  /M18      "Size of child at birth"
  /M19      "Birth weight in kilograms (3 decimals)"
  /M19A     "Weight at birth/recall"
  /M27      "NA - Flag for breastfeeding"
  /M28      "Flag for amenorrhea"
  /M29      "Flag for abstinence"
  /M34      "When child put to breast"
  /M35      "NA - Number of times breastfed during previous night"
  /M36      "NA - Number of times breastfed during previous day"
  /M38      "Drank from bottle with nipple yesterday/last night"
  /M39A     "Did eat any solid, semi-solid or soft foods yesterday"
  /M39      "Number of times ate solid, semi-solid or soft food yesterday"
  /M42A     "NA - During pregnancy: weighed"
  /M42B     "NA - During pregnancy: height measured"
  /M42C     "During pregnancy: blood pressure taken"
  /M42D     "During pregnancy: urine sample taken"
  /M42E     "During pregnancy: blood sample taken"
  /M43      "Told about pregnancy complications"
  /M44      "NA - Told where to go for pregnancy complications"
  /M45      "During pregnancy, given or bought iron tablets/syrup"
  /M46      "Days tablets or syrup taken"
  /M47      "NA - During pregnancy, had difficulty with daylight vision"
  /M48      "NA - During pregnancy, had difficulty with night blindness"
  /M49A     "During pregnancy took: SP/fansidar for malaria"
  /M49B     "During pregnancy took: chloroquine for malaria"
  /M49C     "During pregnancy took: Artemisinin-based Combination (ACT)"
  /M49D     "During pregnancy took: Artesunate or Amodiaquine"
  /M49E     "NA - During pregnancy took: CS drug for malaria"
  /M49F     "NA - During pregnancy took: CS drug for malaria"
  /M49G     "NA - During pregnancy took: CS drug for malaria"
  /M49X     "During pregnancy took: other drug for malaria"
  /M49Z     "During pregnancy took: don't know"
  /M49Y     "During pregnancy took: no drug for malaria"
  /M50      "Respondent's check up after delivery"
  /M51      "Respondent's checkup after deliver timing"
  /M52      "Respondent's health professional checked up after delivery"
  /M54      "Received Vitamin A dose in first 2 months after delivery"
  /M55A     "First 3 days, given milk (other than breast milk)"
  /M55B     "First 3 days, given plain water"
  /M55C     "First 3 days, given sugar/glucose water"
  /M55D     "First 3 days, given gripe water"
  /M55E     "First 3 days, given sugar/salt solution"
  /M55F     "First 3 days, given fruit juice"
  /M55G     "First 3 days, given infant formula"
  /M55H     "First 3 days, given tea/infusions"
  /M55I     "First 3 days, given honey"
  /M55J     "First 3 days, given coffee"
  /M55K     "NA - First 3 days, given country specific"
  /M55L     "NA - First 3 days, given country specific"
  /M55M     "NA - First 3 days, given country specific"
  /M55N     "NA - First 3 days, given country specific"
  /M55O     "NA - First 3 days, given country specific"
  /M55X     "First 3 days, given other"
  /M55Z     "First 3 days, given nothing"
  /M57A     "Antenatal care: respondent's home"
  /M57B     "Antenatal care: other home"
  /M57C     "NA - Antenatal care: CS home"
  /M57D     "NA - Antenatal care: CS home"
  /M57E     "Antenatal care: government hospital"
  /M57F     "Antenatal care: government health center"
  /M57G     "Antenatal care: government health post"
  /M57H     "Antenatal care: other public"
  /M57I     "NA - Antenatal care: CS public health"
  /M57J     "NA - Antenatal care: CS public health"
  /M57K     "NA - Antenatal care: CS public health"
  /M57L     "NA - Antenatal care: CS public health"
  /M57M     "Antenatal care: private hospital/clinic"
  /M57N     "Antenatal care: Other private"
  /M57O     "NA - Antenatal care: CS private medical"
  /M57P     "NA - Antenatal care: CS private medical"
  /M57Q     "NA - Antenatal care: CS private medical"
  /M57R     "NA - Antenatal care: CS private medical"
  /M57S     "NA - Antenatal care: CS other"
  /M57T     "NA - Antenatal care: CS other"
  /M57U     "NA - Antenatal care: CS other"
  /M57V     "NA - Antenatal care: CS other"
  /M57X     "Antenatal care: other"
  /M60      "Drugs for intestinal parasites during pregnancy"
  /M61      "Time spent at place of delivery"
  /M62      "Respondent's health checked before discharge"
  /M65A     "NA - Reason didn't deliver at health facility: cost too much"
  /M65B     "NA - Reason didn't deliver at health facility: facility not open"
  /M65C     "NA - Reason didn't deliver at health facility: too far/no transport"
  /M65D     "NA - Reason didn't deliver at health facility: don't trust facility/poor service"
  /M65E     "NA - Reason didn't deliver at health facility: no female provider"
  /M65F     "NA - Reason didn't deliver at health facility: husband/family didn't allow"
  /M65G     "NA - Reason didn't deliver at health facility: not necessary"
  /M65H     "NA - Reason didn't deliver at health facility: not customary"
  /M65I     "NA - Reason didn't deliver at health facility: CS"
  /M65J     "NA - Reason didn't deliver at health facility: CS"
  /M65K     "NA - Reason didn't deliver at health facility: CS"
  /M65L     "NA - Reason didn't deliver at health facility: CS"
  /M65X     "NA - Reason didn't deliver at health facility: other"
  /M66      "Respondent's health checked after discharge/delivery at home"
  /M70      "Baby postnatal check within 2 months"
  /M71      "Time after delivery postnatal check took place"
  /M72      "Person who performed postnatal checkup"
  /M73      "Place baby was first checked"
  /HIDX     "Index to birth history"
  /H1       "Has health card"
  /H2       "Received BCG"
  /H2D      "BCG day"
  /H2M      "BCG month"
  /H2Y      "BCG year"
  /H3       "Received DPT 1"
  /H3D      "DPT 1 day"
  /H3M      "DPT 1 month"
  /H3Y      "DPT 1 year"
  /H4       "Received POLIO 1"
  /H4D      "POLIO 1 day"
  /H4M      "POLIO 1 month"
  /H4Y      "POLIO 1 year"
  /H5       "Received DPT 2"
  /H5D      "DPT 2 day"
  /H5M      "DPT 2 month"
  /H5Y      "DPT 2 year"
  /H6       "Received POLIO 2"
  /H6D      "POLIO 2 day"
  /H6M      "POLIO 2 month"
  /H6Y      "POLIO 2 year"
  /H7       "Received DPT 3"
  /H7D      "DPT 3 day"
  /H7M      "DPT 3 month"
  /H7Y      "DPT 3 year"
  /H8       "Received POLIO 3"
  /H8D      "POLIO 3 day"
  /H8M      "POLIO 3 month"
  /H8Y      "POLIO 3 year"
  /H9       "Received MEASLES"
  /H9D      "MEASLES day"
  /H9M      "MEASLES month"
  /H9Y      "MEASLES year"
  /H0       "Received POLIO 0"
  /H0D      "POLIO 0 day"
  /H0M      "POLIO 0 month"
  /H0Y      "POLIO 0 year"
  /H10      "Ever had vaccination"
  /H11      "Had diarrhea recently"
  /H11B     "Blood in the stools"
  /H12A     "Diarrhea: government hospital"
  /H12B     "Diarrhea: government health center"
  /H12C     "Diarrhea: government health post"
  /H12D     "Diarrhea: public mobile clinic"
  /H12E     "Diarrhea: public health worker"
  /H12F     "Diarrhea: other public"
  /H12G     "NA - Diarrhea: CS public sector"
  /H12H     "NA - Diarrhea: CS public sector"
  /H12I     "NA - Diarrhea: CS public sector"
  /H12J     "Diarrhea: private hospital/clinic"
  /H12K     "Diarrhea: pharmacy"
  /H12L     "Diarrhea: private doctor"
  /H12M     "Diarrhea: private mobile clinic"
  /H12N     "Diarrhea: private health worker"
  /H12O     "Diarrhea: other private"
  /H12P     "NA - Diarrhea: CS private medical"
  /H12Q     "NA - Diarrhea: CS private medical"
  /H12R     "NA - Diarrhea: CS private medical"
  /H12S     "Diarrhea: shop"
  /H12T     "Diarrhea: traditional practitioner"
  /H12U     "Diarrhea: market"
  /H12V     "NA - Diarrhea: CS other sector"
  /H12W     "NA - Diarrhea: CS other sector"
  /H12X     "Diarrhea: Other"
  /H12Y     "Diarrhea: no treatment"
  /H12Z     "Diarrhea: medical treatment"
  /H13      "Given oral rehydration"
  /H13B     "NA - Given pre-packaged ORS liquid"
  /H14      "Given recommended home solution"
  /H15      "Given antibiotic pills or syrups"
  /H15A     "Given antimotility"
  /H15B     "Given antibiotic injection"
  /H15C     "Given intravenous (IV)"
  /H15D     "Given home remedy, herbal medicine"
  /H15E     "Given zinc"
  /H15F     "Given other (not antibiotic, antimotility, zinc)"
  /H15G     "Given unknown pill or syrup"
  /H15H     "Given non-antibiotic injection"
  /H15I     "Given unknown injection"
  /H15J     "NA - Given CS"
  /H15K     "NA - Given CS"
  /H15L     "NA - Given CS"
  /H15M     "NA - Given CS"
  /H20      "Given other treatment"
  /H21A     "Given no treatment"
  /H21      "Received any treatment"
  /H22      "Had fever in last two weeks"
  /H31      "Had cough in last two weeks"
  /H31B     "Short, rapid breaths"
  /H31C     "Problem in the chest or blocked or running nose"
  /H31D     "Had fever/cough in last 2 weeks: amount offered to drink"
  /H31E     "Had fever/cough in last 2 weeks: amount offered to eat"
  /H32A     "Fever/cough: government hospital"
  /H32B     "Fever/cough: government health center"
  /H32C     "Fever/cough: government health post"
  /H32D     "Fever/cough: public mobile clinic"
  /H32E     "Fever/cough: public health worker"
  /H32F     "Fever/cough: community health worker"
  /H32G     "Fever/cough: other public"
  /H32H     "NA - Fever/cough: CS public sector"
  /H32I     "NA - Fever/cough: CS public sector"
  /H32J     "Fever/cough: private hospital/ clinic"
  /H32K     "Fever/cough: private pharmacy"
  /H32L     "Fever/cough: private doctor"
  /H32M     "Fever/cough: private mobile clinic"
  /H32N     "Fever/cough: private health worker"
  /H32O     "Fever/cough: other private"
  /H32P     "NA - Fever/cough: CS private medical"
  /H32Q     "NA - Fever/cough: CS private medical"
  /H32R     "NA - Fever/cough: CS private medical"
  /H32S     "Fever/cough: shop"
  /H32T     "Fever/cough: traditional practitioner"
  /H32U     "Fever/cough: market"
  /H32V     "NA - Fever/cough: CS other sector"
  /H32W     "NA - Fever/cough: CS other sector"
  /H32X     "Fever/cough: other"
  /H32Y     "Fever/cough: no treatment"
  /H32Z     "Fever/cough: medical treatment"
  /H33      "Received Vitamin A1 (most recent)"
  /H33D     "Vitamin A1 day"
  /H33M     "Vitamin A1 month"
  /H33Y     "Vitamin A1 year"
  /H34      "Vitamin A in last 6 months"
  /H35      "NA - Any vaccinations in last 2 years part of campaign"
  /H36A     "NA - Vaccinated during Campaign A"
  /H36B     "NA - Vaccinated during Campaign B"
  /H36C     "NA - Vaccinated during Campaign C"
  /H36D     "NA - Vaccinated during Campaign D"
  /H36E     "NA - Vaccinated during Campaign E"
  /H36F     "NA - Vaccinated during Campaign F"
  /H37A     "NA - SP/Fansidar taken for fever/cough"
  /H37B     "NA - Chloroquine taken for fever/cough"
  /H37C     "NA - Amodiaquine taken for fever/cough"
  /H37D     "NA - Quinine taken for fever/cough"
  /H37E     "NA - Combination with artemisinin taken for fever/cough"
  /H37F     "NA - CS antimalarial taken for fever/cough"
  /H37G     "NA - CS antimalarial taken for fever/cough"
  /H37H     "NA - Other antimalarial taken for fever/cough"
  /H37I     "NA - Antibiotic pill/syrup taken for fever/cough"
  /H37J     "NA - Antibiotic injection taken for fever/cough"
  /H37K     "NA - Aspirin taken for fever/cough"
  /H37L     "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
  /H37M     "NA - Ibuprofen taken for fever/cough"
  /H37N     "NA - CS other taken for fever/cough"
  /H37O     "NA - CS other for fever/cough"
  /H37P     "NA - CS other for fever/cough"
  /H37X     "NA - Other taken for fever/cough"
  /H37Y     "NA - Nothing taken for fever/cough"
  /H37Z     "NA - Don't know if or what was taken for fever/cough"
  /H38      "Diarrhea in last 2 weeks: amount offered to drink"
  /H39      "Diarrhea in last 2 weeks: amount offered to eat"
  /H40      "NA - Received Vitamin A2 (2nd most recent)"
  /H40D     "NA - Vitamin A2 day"
  /H40M     "NA - Vitamin A2 month"
  /H40Y     "NA - Vitamin A2 year"
  /H41A     "NA - Received vitamin A after most recent in card"
  /H41B     "NA - Ever received Vitamin A dose"
  /H42      "Taking iron pills, sprinkles or syrup"
  /H43      "Drugs for intestinal parasites in last 6 months"
  /H44A     "Place first sought treatment for diarrhea"
  /H44B     "NA - Days after diarrhea sought advice or treatment"
  /H44C     "NA - Still has diarrhea"
  /H45      "NA - Times zinc was given"
  /H46A     "Place first sought treatment for fever"
  /H46B     "NA - Days after fever sought advice or treatment"
  /H47      "Blood taken from child's finger/heel for testing"
  /HWIDX    "Index to Birth History"
  /HW1      "Child's age in months"
  /HW2      "Child's weight in kilograms (1 decimal)"
  /HW3      "Child's height in centimeters (1 decimal)"
  /HW4      "Height/Age percentile"
  /HW5      "Height/Age standard deviation"
  /HW6      "Height/Age percent of ref. median"
  /HW7      "Weight/Age percentile"
  /HW8      "Weight/Age standard deviation"
  /HW9      "Weight/Age percent of ref. median"
  /HW10     "Weight/Height percentile"
  /HW11     "Weight/Height standard deviation"
  /HW12     "Weight/Height percent of ref. median"
  /HW13     "Result of measurement - height/weight"
  /HW15     "Height: lying or standing"
  /HW16     "Day of birth of child"
  /HW17     "Date measured (day)"
  /HW18     "Date measured (month)"
  /HW19     "Date measured (year)"
  /HW51     "Line number of parent/caretaker"
  /HW52     "Read consent statement - hemoglobin"
  /HW53     "Hemoglobin level (g/dl - 1 decimal)"
  /HW55     "Result of measurement - hemoglobin"
  /HW56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
  /HW57     "Anemia level"
  /HW58     "NA - Agrees to referral - anemia"
  /HW70     "Height/Age standard deviation (new WHO)"
  /HW71     "Weight/Age standard deviation (new WHO)"
  /HW72     "Weight/Height standard deviation (new WHO)"
  /HW73     "BMI standard deviation (new WHO)"
  /IDXML    "Index to Birth History"
  /ML0      "Type of mosquito bed net(s) child slept under last night"
  /ML1      "Number of times took fansidar during pregnancy"
  /ML2      "Source of antimalarial during pregnancy"
  /ML11     "NA - Child has fever/cough now"
  /ML12     "NA - Child has had convulsions in last 2 weeks"
  /ML13A    "Fansidar taken for fever/cough"
  /ML13B    "Chloroquine taken for fever/cough"
  /ML13C    "NA - Amodiaquine taken for fever/cough"
  /ML13D    "Quinine taken for fever/cough"
  /ML13E    "Combination with artemisinin taken for fever/cough"
  /ML13F    "NA - CS taken for fever/cough"
  /ML13G    "Artesunate antimalarial taken for fever/cough"
  /ML13H    "Other antimalarial taken for fever/cough"
  /ML13I    "Antibiotic pill/syrup taken for fever/cough"
  /ML13J    "Antibiotic injection taken for fever/cough"
  /ML13K    "Aspirin taken for fever/cough"
  /ML13L    "Acetaminophen/paracetamol/panadol taken for fever/cough"
  /ML13M    "Ibuprofen taken for fever/cough"
  /ML13N    "Other country specific taken for fever/cough"
  /ML13O    "Other country specific taken for fever/cough"
  /ML13P    "Other country specific taken for fever/cough"
  /ML13X    "Other taken for fever/cough"
  /ML13Y    "Nothing taken for fever/cough"
  /ML13Z    "Don't know if or what was taken for fever/cough"
  /ML14A    "NA - Injection given for fever/convulsion"
  /ML14B    "NA - Suppository given for fever/convulsion"
  /ML14Y    "NA - No suppository or injection given for fever/convulsion"
  /ML14Z    "NA - Don't know if suppository or injection given for fever/convulsion"
  /ML15A    "Timing of start of fansidar"
  /ML15B    "NA - Number of days child took fansidar"
  /ML15C    "NA - First source for fansidar"
  /ML16A    "Timing of start of chloroquine"
  /ML16B    "NA - Number of days child took chloroquine"
  /ML16C    "NA - First source for chloroquine"
  /ML17A    "NA - Timing of start of amodiaquine"
  /ML17B    "NA - Number of days child took amodiaquine"
  /ML17C    "NA - First source for amodiaquine"
  /ML18A    "Timing of start of quinine"
  /ML18B    "NA - Number of days child took quinine"
  /ML18C    "NA - First source for quinine"
  /ML19A    "NA - For fever/convulsion: consulted traditional healer"
  /ML19B    "NA - For fever/convulsion: gave tepid sponging"
  /ML19C    "NA - For fever/convulsion: gave herbs"
  /ML19D    "NA - For fever/convulsion: CS"
  /ML19E    "NA - For fever/convulsion: CS"
  /ML19F    "NA - For fever/convulsion: CS"
  /ML19X    "NA - For fever/convulsion: other"
  /ML19Y    "NA - For fever/convulsion: gave/did nothing"
  /ML19Z    "NA - For fever/convulsion: don't know if something else was done"
  /ML20A    "Timing of start of combination with artemisinin"
  /ML20B    "NA - Number of days child took combination with artemisinin"
  /ML20C    "NA - First source for combination with artemisinin"
  /ML21A    "Timing of start of CS antimalarial use"
  /ML21B    "NA - Number of days child took CS antimalarial"
  /ML21C    "NA - First source for CS antimalarial"
  /ML22A    "NA - Timing of start of CS antimalarial use"
  /ML22B    "NA - Number of days child took CS antimalarial"
  /ML22C    "NA - First source for CS antimalarial"
  /ML23A    "Timing of start of other anti-malarial use"
  /ML23B    "NA - Number of days child took other anti-malarial"
  /ML23C    "NA - First source for other anti-malarial"
  /ML24C    "NA - First source for antibiotic pill/syrup"
  /G100     "Ever heard of female circumcision"
  /G101     "Ever heard of genital cutting (probed)"
  /G102     "Respondent circumcised"
  /G103     "Flesh removed from genital area"
  /G104     "Genital area just nicked without removing any flesh"
  /G105     "Genital area sewn closed"
  /G106     "Age at circumcision (in years)"
  /G107     "Person who performed circumcision"
  /G108     "Number of daughters circumcised"
  /G109     "Line number of daughter most recently circumcised (from Birth History)"
  /G110     "Flesh removed from genital area of daughter"
  /G111     "Genital area of daughter just nicked without removing flesh"
  /G112     "Genital area of daughter sewn closed"
  /G113     "Age of daughter at circumcision (in years)"
  /G114     "Person who performed circumcision of daughter"
  /G115     "Any daughter not circumcised"
  /G116     "Intends to have daughter(s) circumcised in future"
  /G117A    "Cleanliness/hygiene: Female circumcision benefit"
  /G117B    "Social acceptance: Female circumcision benefit"
  /G117C    "Better marriage prospects: Female circumcision benefit"
  /G117D    "Virginity/prevent premarital sex: Female circumcision benefit"
  /G117E    "Greater sexual pleasure for men: Female circumcision benefit"
  /G117F    "Religious approval: Female circumcision benefit"
  /G117G    "NA - CS: Female circumcision benefit"
  /G117H    "NA - CS: Female circumcision benefit"
  /G117I    "NA - CS: Female circumcision benefit"
  /G117J    "No opinion/Don't know: Female circumcision benefit"
  /G117X    "Other: Female circumcision benefit"
  /G117Y    "No benefit from female circumcision"
  /G118     "Female circumcision required by religion"
  /G119     "Female circumcision: continue or be stopped"
  /SZONE    "Geographical zone"
  /SHREG    "Health regions"
  /IDX94    "Index to Birth History"
  /S426     "Took SP/Fansidar during antenatal visit (Malaria)"
  /IDX95    "Index to Birth History"
  /SYF      "Received yellow fever"
  /SYFD     "Yellow fever day"
  /SYFM     "Yellow fever Month"
  /SYFY     "Yellow fever Year"
  /SPC1     "Received PCV 1"
  /SPC1D    "PCV 1 Day"
  /SPC1M    "PCV 1 Month"
  /SPC1Y    "PCV 1 Year"
  /SPC2     "Received PCV 2"
  /SPC2D    "PCV 2 Day"
  /SPC2M    "PCV 2 Month"
  /SPC2Y    "PCV 2 Year"
  /SPC3     "Received PCV 3"
  /SPC3D    "PCV 3 Day"
  /SPC3M    "PCV 3 Month"
  /SPC3Y    "PCV 3 Year"
  /SHP0     "Received Hepatitis B0"
  /SHB0D    "Hepatitis B0 Day"
  /SHB0M    "Hepatitis B0 Month"
  /SHB0Y    "Hepatitis B0 Year"
 .
MISSING VALUE
   V026     (9)
  /V027     (9)
  /V028     (999)
  /V029     (99)
  /V030     (999)
  /V031     (999)
  /V032     (99)
  /V034     (99)
  /V040     (9999)
  /V103     (9)
  /V104     (99)
  /V105     (9)
  /V106     (9)
  /V107     (99)
  /V113     (99)
  /V115     (999)
  /V116     (99)
  /V119     (9)
  /V120     (9)
  /V121     (9)
  /V122     (9)
  /V123     (9)
  /V124     (9)
  /V125     (9)
  /V127     (99)
  /V128     (99)
  /V129     (99)
  /V130     (99)
  /V131     (999)
  /V133     (99)
  /V134     (9)
  /V135     (9)
  /V139     (99)
  /V140     (9)
  /V141     (9)
  /V149     (9)
  /V150     (99)
  /V152     (99)
  /V153     (9)
  /V155     (9)
  /V156     (9)
  /V157     (9)
  /V158     (9)
  /V159     (9)
  /V160     (9)
  /V161     (99)
  /V166     (999)
  /V167     (99)
  /V168     (9)
  /ML101    (9)
  /V215     (999)
  /V217     (9)
  /V225     (9)
  /V226     (999)
  /V228     (9)
  /V229     (99)
  /V230     (9999)
  /V231     (9999)
  /V233     (99)
  /V234     (9)
  /V237     (9)
  /V239     (9)
  /V240     (99)
  /V241     (9999)
  /V242     (9999)
  /V310     (99)
  /V311     (9)
  /V312     (99)
  /V313     (9)
  /V323     (99)
  /V323A    (99)
  /V325A    (9999999)
  /V326     (99)
  /V327     (9)
  /V337     (999)
  /V359     (99)
  /V360     (99)
  /V362     (9)
  /V363     (99)
  /V367     (9)
  /V372     (9)
  /V372A    (9)
  /V375A    (99)
  /V376     (99)
  /V376A    (9)
  /V379     (99)
  /V380     (9)
  /V384A    (9)
  /V384B    (9)
  /V384C    (9)
  /V393     (9)
  /V394     (9)
  /V395     (9)
  /V3A00A   (9)
  /V3A00B   (9)
  /V3A00C   (9)
  /V3A00D   (9)
  /V3A00E   (9)
  /V3A00F   (9)
  /V3A00G   (9)
  /V3A00H   (9)
  /V3A00I   (9)
  /V3A00J   (9)
  /V3A00K   (9)
  /V3A00L   (9)
  /V3A00M   (9)
  /V3A00N   (9)
  /V3A00O   (9)
  /V3A00P   (9)
  /V3A00Q   (9)
  /V3A00R   (9)
  /V3A00S   (9)
  /V3A00T   (9)
  /V3A00U   (9)
  /V3A00V   (9)
  /V3A00W   (9)
  /V3A00X   (9)
  /V3A00Y   (9)
  /V3A00Z   (9)
  /V3A01    (9)
  /V3A02    (9)
  /V3A03    (9)
  /V3A04    (9)
  /V3A05    (9)
  /V3A06    (9)
  /V3A07    (99)
  /V3A08A   (9)
  /V3A08B   (9)
  /V3A08C   (9)
  /V3A08D   (9)
  /V3A08E   (9)
  /V3A08F   (9)
  /V3A08G   (9)
  /V3A08H   (9)
  /V3A08I   (9)
  /V3A08J   (9)
  /V3A08K   (9)
  /V3A08L   (9)
  /V3A08M   (9)
  /V3A08N   (9)
  /V3A08O   (9)
  /V3A08P   (9)
  /V3A08Q   (9)
  /V3A08R   (9)
  /V3A08S   (9)
  /V3A08T   (9)
  /V3A08U   (9)
  /V3A08V   (9)
  /V3A08W   (9)
  /V3A08AA  (9)
  /V3A08AB  (9)
  /V3A08AC  (9)
  /V3A08AD  (9)
  /V3A08X   (9)
  /V3A08Z   (9)
  /V3A09A   (999)
  /V3A09B   (999)
  /V401     (9)
  /V407     (99)
  /V408     (99)
  /V409     (9)
  /V409A    (9)
  /V410     (9)
  /V410A    (9)
  /V411     (9)
  /V411A    (9)
  /V412     (9)
  /V412A    (9)
  /V412B    (9)
  /V412C    (9)
  /V413     (9)
  /V413A    (9)
  /V413B    (9)
  /V413C    (9)
  /V413D    (9)
  /V414A    (9)
  /V414B    (9)
  /V414C    (9)
  /V414D    (9)
  /V414E    (9)
  /V414F    (9)
  /V414G    (9)
  /V414H    (9)
  /V414I    (9)
  /V414J    (9)
  /V414K    (9)
  /V414L    (9)
  /V414M    (9)
  /V414N    (9)
  /V414O    (9)
  /V414P    (9)
  /V414Q    (9)
  /V414R    (9)
  /V414S    (9)
  /V414T    (9)
  /V414U    (9)
  /V414V    (9)
  /V414W    (9)
  /V415     (9)
  /V416     (9)
  /V420     (999)
  /V421     (999)
  /V426     (999)
  /V437     (9999)
  /V438     (9999)
  /V439     (9999)
  /V440     (9999)
  /V441     (99999)
  /V442     (99999)
  /V443     (99999)
  /V444     (99999)
  /V444A    (9999)
  /V445     (9999)
  /V446     (9999)
  /V447     (9)
  /V452A    (9)
  /V452B    (99)
  /V452C    (9)
  /V453     (999)
  /V454     (9)
  /V455     (9)
  /V456     (999)
  /V457     (9)
  /V458     (9)
  /V459     (9)
  /V460     (9)
  /V461     (9)
  /V462     (9)
  /V463A    (9)
  /V463B    (9)
  /V463C    (9)
  /V463D    (9)
  /V463E    (9)
  /V463F    (9)
  /V463G    (9)
  /V463X    (9)
  /V463Z    (9)
  /V464     (99)
  /V465     (99)
  /V466     (9)
  /V467A    (9)
  /V467B    (9)
  /V467C    (9)
  /V467D    (9)
  /V467E    (9)
  /V467F    (9)
  /V467G    (9)
  /V467H    (9)
  /V467I    (9)
  /V467J    (9)
  /V467K    (9)
  /V467L    (9)
  /V467M    (9)
  /V469E    (9)
  /V469F    (9)
  /V469X    (9)
  /V471A    (9)
  /V471B    (9)
  /V471C    (9)
  /V471D    (9)
  /V471E    (9)
  /V471F    (9)
  /V471G    (9)
  /V472A    (9)
  /V472B    (9)
  /V472C    (9)
  /V472D    (9)
  /V472E    (9)
  /V472F    (9)
  /V472G    (9)
  /V472H    (9)
  /V472I    (9)
  /V472J    (9)
  /V472K    (9)
  /V472L    (9)
  /V472M    (9)
  /V472N    (9)
  /V472O    (9)
  /V472P    (9)
  /V472Q    (9)
  /V472R    (9)
  /V472S    (9)
  /V472T    (9)
  /V472U    (9)
  /V473A    (9)
  /V473B    (9)
  /V474     (9)
  /V474A    (9)
  /V474B    (9)
  /V474C    (9)
  /V474D    (9)
  /V474E    (9)
  /V474F    (9)
  /V474G    (9)
  /V474H    (9)
  /V474I    (9)
  /V474J    (9)
  /V474X    (9)
  /V474Z    (9)
  /V475     (9)
  /V476     (9)
  /V477     (99)
  /V478     (99)
  /V479     (99)
  /V480     (9)
  /V481     (9)
  /V481A    (9)
  /V481B    (9)
  /V481C    (9)
  /V481D    (9)
  /V481E    (9)
  /V481F    (9)
  /V481G    (9)
  /V481H    (9)
  /V481X    (9)
  /V482A    (9)
  /V482B    (9)
  /V482C    (9)
  /V501     (9)
  /V502     (9)
  /V503     (9)
  /V504     (9)
  /V505     (99)
  /V506     (99)
  /V525     (99)
  /V527     (999)
  /V528     (99)
  /V529     (999)
  /V531     (99)
  /V535     (9)
  /V536     (9)
  /V537     (99)
  /V538     (9)
  /V539     (9)
  /V540     (9)
  /V541     (9)
  /V602     (9)
  /V603     (999)
  /V604     (9)
  /V605     (9)
  /V613     (99)
  /V616     (999)
  /V621     (9)
  /V623     (9)
  /V624     (99)
  /V625     (9)
  /V626     (99)
  /V625A    (9)
  /V626A    (99)
  /V627     (99)
  /V628     (99)
  /V629     (99)
  /V631     (9)
  /V632     (9)
  /V633A    (9)
  /V633B    (9)
  /V633C    (9)
  /V633D    (9)
  /V633E    (9)
  /V633F    (9)
  /V633G    (9)
  /V634     (9)
  /V701     (9)
  /V702     (99)
  /V704     (999)
  /V705     (99)
  /V714     (9)
  /V714A    (9)
  /V715     (99)
  /V716     (999)
  /V717     (99)
  /V719     (9)
  /V721     (9)
  /V729     (9)
  /V730     (99)
  /V731     (9)
  /V732     (9)
  /V739     (9)
  /V740     (9)
  /V741     (9)
  /V743A    (9)
  /V743B    (9)
  /V743C    (9)
  /V743D    (9)
  /V743E    (9)
  /V743F    (9)
  /V744A    (9)
  /V744B    (9)
  /V744C    (9)
  /V744D    (9)
  /V744E    (9)
  /V745A    (9)
  /V745B    (9)
  /V746     (9)
  /B6       (999)
  /B9       (9)
  /B15      (9)
  /B16      (99)
  /M1       (9)
  /M1A      (9)
  /M1B      (99)
  /M1C      (9999)
  /M1D      (99)
  /M2A      (9)
  /M2B      (9)
  /M2C      (9)
  /M2D      (9)
  /M2E      (9)
  /M2F      (9)
  /M2G      (9)
  /M2H      (9)
  /M2I      (9)
  /M2J      (9)
  /M2K      (9)
  /M2L      (9)
  /M2M      (9)
  /M2N      (9)
  /M3A      (9)
  /M3B      (9)
  /M3C      (9)
  /M3D      (9)
  /M3E      (9)
  /M3F      (9)
  /M3G      (9)
  /M3H      (9)
  /M3I      (9)
  /M3J      (9)
  /M3K      (9)
  /M3L      (9)
  /M3M      (9)
  /M3N      (9)
  /M4       (99)
  /M5       (99)
  /M6       (99)
  /M7       (99)
  /M8       (99)
  /M9       (99)
  /M10      (9)
  /M11      (999)
  /M13      (99)
  /M14      (99)
  /M15      (99)
  /M17      (9)
  /M18      (9)
  /M19      (9999)
  /M34      (999)
  /M35      (99)
  /M36      (99)
  /M38      (9)
  /M39A     (9)
  /M39      (9)
  /M42A     (9)
  /M42B     (9)
  /M42C     (9)
  /M42D     (9)
  /M42E     (9)
  /M43      (9)
  /M44      (9)
  /M45      (9)
  /M46      (999)
  /M47      (9)
  /M48      (9)
  /M49A     (9)
  /M49B     (9)
  /M49C     (9)
  /M49D     (9)
  /M49E     (9)
  /M49F     (9)
  /M49G     (9)
  /M49X     (9)
  /M49Z     (9)
  /M49Y     (9)
  /M50      (9)
  /M51      (999)
  /M52      (99)
  /M54      (9)
  /M55A     (9)
  /M55B     (9)
  /M55C     (9)
  /M55D     (9)
  /M55E     (9)
  /M55F     (9)
  /M55G     (9)
  /M55H     (9)
  /M55I     (9)
  /M55J     (9)
  /M55K     (9)
  /M55L     (9)
  /M55M     (9)
  /M55N     (9)
  /M55O     (9)
  /M55X     (9)
  /M55Z     (9)
  /M57A     (9)
  /M57B     (9)
  /M57C     (9)
  /M57D     (9)
  /M57E     (9)
  /M57F     (9)
  /M57G     (9)
  /M57H     (9)
  /M57I     (9)
  /M57J     (9)
  /M57K     (9)
  /M57L     (9)
  /M57M     (9)
  /M57N     (9)
  /M57O     (9)
  /M57P     (9)
  /M57Q     (9)
  /M57R     (9)
  /M57S     (9)
  /M57T     (9)
  /M57U     (9)
  /M57V     (9)
  /M57X     (9)
  /M60      (9)
  /M61      (999)
  /M62      (9)
  /M65A     (9)
  /M65B     (9)
  /M65C     (9)
  /M65D     (9)
  /M65E     (9)
  /M65F     (9)
  /M65G     (9)
  /M65H     (9)
  /M65I     (9)
  /M65J     (9)
  /M65K     (9)
  /M65L     (9)
  /M65X     (9)
  /M66      (9)
  /M70      (9)
  /M71      (999)
  /M72      (99)
  /M73      (99)
  /H1       (9)
  /H2       (9)
  /H2D      (99)
  /H2M      (99)
  /H2Y      (9999)
  /H3       (9)
  /H3D      (99)
  /H3M      (99)
  /H3Y      (9999)
  /H4       (9)
  /H4D      (99)
  /H4M      (99)
  /H4Y      (9999)
  /H5       (9)
  /H5D      (99)
  /H5M      (99)
  /H5Y      (9999)
  /H6       (9)
  /H6D      (99)
  /H6M      (99)
  /H6Y      (9999)
  /H7       (9)
  /H7D      (99)
  /H7M      (99)
  /H7Y      (9999)
  /H8       (9)
  /H8D      (99)
  /H8M      (99)
  /H8Y      (9999)
  /H9       (9)
  /H9D      (99)
  /H9M      (99)
  /H9Y      (9999)
  /H0       (9)
  /H0D      (99)
  /H0M      (99)
  /H0Y      (9999)
  /H10      (9)
  /H11      (9)
  /H11B     (9)
  /H12A     (9)
  /H12B     (9)
  /H12C     (9)
  /H12D     (9)
  /H12E     (9)
  /H12F     (9)
  /H12G     (9)
  /H12H     (9)
  /H12I     (9)
  /H12J     (9)
  /H12K     (9)
  /H12L     (9)
  /H12M     (9)
  /H12N     (9)
  /H12O     (9)
  /H12P     (9)
  /H12Q     (9)
  /H12R     (9)
  /H12S     (9)
  /H12T     (9)
  /H12U     (9)
  /H12V     (9)
  /H12W     (9)
  /H12X     (9)
  /H12Y     (9)
  /H12Z     (9)
  /H13      (9)
  /H13B     (9)
  /H14      (9)
  /H15      (9)
  /H15A     (9)
  /H15B     (9)
  /H15C     (9)
  /H15D     (9)
  /H15E     (9)
  /H15F     (9)
  /H15G     (9)
  /H15H     (9)
  /H15I     (9)
  /H15J     (9)
  /H15K     (9)
  /H15L     (9)
  /H15M     (9)
  /H20      (9)
  /H21A     (9)
  /H21      (9)
  /H22      (9)
  /H31      (9)
  /H31B     (9)
  /H31C     (9)
  /H31D     (9)
  /H31E     (9)
  /H32A     (9)
  /H32B     (9)
  /H32C     (9)
  /H32D     (9)
  /H32E     (9)
  /H32F     (9)
  /H32G     (9)
  /H32H     (9)
  /H32I     (9)
  /H32J     (9)
  /H32K     (9)
  /H32L     (9)
  /H32M     (9)
  /H32N     (9)
  /H32O     (9)
  /H32P     (9)
  /H32Q     (9)
  /H32R     (9)
  /H32S     (9)
  /H32T     (9)
  /H32U     (9)
  /H32V     (9)
  /H32W     (9)
  /H32X     (9)
  /H32Y     (9)
  /H32Z     (9)
  /H33      (9)
  /H33D     (99)
  /H33M     (99)
  /H33Y     (9999)
  /H34      (9)
  /H35      (9)
  /H36A     (9)
  /H36B     (9)
  /H36C     (9)
  /H36D     (9)
  /H36E     (9)
  /H36F     (9)
  /H37A     (9)
  /H37B     (9)
  /H37C     (9)
  /H37D     (9)
  /H37E     (9)
  /H37F     (9)
  /H37G     (9)
  /H37H     (9)
  /H37I     (9)
  /H37J     (9)
  /H37K     (9)
  /H37L     (9)
  /H37M     (9)
  /H37N     (9)
  /H37O     (9)
  /H37P     (9)
  /H37X     (9)
  /H37Y     (9)
  /H37Z     (9)
  /H38      (9)
  /H39      (9)
  /H40      (9)
  /H40D     (99)
  /H40M     (99)
  /H40Y     (9999)
  /H41A     (9)
  /H41B     (9)
  /H42      (9)
  /H43      (9)
  /H44A     (99)
  /H44B     (99)
  /H44C     (9)
  /H45      (99)
  /H46A     (99)
  /H46B     (99)
  /H47      (9)
  /HW2      (9999)
  /HW3      (9999)
  /HW4      (9999)
  /HW5      (9999)
  /HW6      (99999)
  /HW7      (9999)
  /HW8      (9999)
  /HW9      (99999)
  /HW10     (9999)
  /HW11     (9999)
  /HW12     (99999)
  /HW13     (9)
  /HW15     (9)
  /HW16     (99)
  /HW51     (99)
  /HW52     (9)
  /HW53     (999)
  /HW55     (9)
  /HW56     (9999)
  /HW57     (9)
  /HW58     (9)
  /HW70     (9999)
  /HW71     (9999)
  /HW72     (9999)
  /HW73     (9999)
  /ML0      (9)
  /ML1      (99)
  /ML2      (9)
  /ML11     (9)
  /ML12     (9)
  /ML13A    (9)
  /ML13B    (9)
  /ML13C    (9)
  /ML13D    (9)
  /ML13E    (9)
  /ML13F    (9)
  /ML13G    (9)
  /ML13H    (9)
  /ML13I    (9)
  /ML13J    (9)
  /ML13K    (9)
  /ML13L    (9)
  /ML13M    (9)
  /ML13N    (9)
  /ML13O    (9)
  /ML13P    (9)
  /ML13X    (9)
  /ML13Y    (9)
  /ML13Z    (9)
  /ML14A    (9)
  /ML14B    (9)
  /ML14Y    (9)
  /ML14Z    (9)
  /ML15A    (9)
  /ML15B    (9)
  /ML15C    (9)
  /ML16A    (9)
  /ML16B    (9)
  /ML16C    (9)
  /ML17A    (9)
  /ML17B    (9)
  /ML17C    (9)
  /ML18A    (9)
  /ML18B    (9)
  /ML18C    (9)
  /ML19A    (9)
  /ML19B    (9)
  /ML19C    (9)
  /ML19D    (9)
  /ML19E    (9)
  /ML19F    (9)
  /ML19X    (9)
  /ML19Y    (9)
  /ML19Z    (9)
  /ML20A    (9)
  /ML20B    (9)
  /ML20C    (9)
  /ML21A    (9)
  /ML21B    (9)
  /ML21C    (9)
  /ML22A    (9)
  /ML22B    (9)
  /ML22C    (9)
  /ML23A    (9)
  /ML23B    (9)
  /ML23C    (9)
  /ML24C    (9)
  /G100     (9)
  /G101     (9)
  /G102     (9)
  /G103     (9)
  /G104     (9)
  /G105     (9)
  /G106     (99)
  /G107     (99)
  /G108     (99)
  /G109     (99)
  /G110     (9)
  /G111     (9)
  /G112     (9)
  /G113     (99)
  /G114     (99)
  /G115     (9)
  /G116     (9)
  /G117A    (9)
  /G117B    (9)
  /G117C    (9)
  /G117D    (9)
  /G117E    (9)
  /G117F    (9)
  /G117G    (9)
  /G117H    (9)
  /G117I    (9)
  /G117J    (9)
  /G117X    (9)
  /G117Y    (9)
  /G118     (9)
  /G119     (9)
  /S426     (9)
  /SYF      (9)
  /SPC1     (9)
  /SPC2     (9)
  /SPC3     (9)
  /SHP0     (9)
 .
VALUE LABELS
   V013    
      1 "15-19"
      2 "20-24"
      3 "25-29"
      4 "30-34"
      5 "35-39"
      6 "40-44"
      7 "45-49"
  /V014    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /V015    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partially completed"
      6 "Respondent incapacitated"
      7 "Other"
  /V018    
      0 "No calendar"
  /V019    
      0 "No calendar"
  /V019A   
      0 "No calendar"
  /V020    
      0 "All woman sample"
      1 "Ever married sample"
  /V023    
      1 "Region 1 - urban"
      2 "Region 1 - rural"
      3 "Region 2 - urban"
      4 "Region 2 - rural"
      5 "Region 3 - urban"
      6 "Region 3 - rural"
      7 "Region 4 - urban"
      8 "Region 4 - rural"
  /V024    
      1 "Region 1"
      2 "Region 2"
      3 "Region 3"
      4 "Region 4"
  /V025    
      1 "Urban"
      2 "Rural"
  /V026    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /V034    
      0 "Husband not in household"
  /V042    
      0 "Not selected"
      1 "Selected"
  /V044    
      0 "Woman not selected"
      1 "Woman selected and interviewed"
      2 "Woman selected, but privacy not possible"
      3 "Woman selected, but not interviewed"
  /V101    
      1 "Region 1"
      2 "Region 2"
      3 "Region 3"
      4 "Region 4"
  /V102    
      1 "Urban"
      2 "Rural"
  /V103    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
  /V104    
     95 "Always"
     96 "Visitor"
     97 "Inconsistent"
     98 "Don't know"
  /V105    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
  /V106    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
  /V107    
      0 "No years completed at level V106"
  /V113    
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE WATER"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water or sachets"
     96 "Other"
     97 "Not a dejure resident"
  /V115    
    996 "On premises"
    997 "Not a dejure resident"
    998 "Don't know"
  /V116    
     10 "FLUSH TOILET"
     11 "Flush to piped sewer system"
     12 "Flush to septic tank"
     13 "Flush to pit latrine"
     14 "Flush to somewhere else"
     15 "Flush, don't know where"
     20 "PIT TOILET LATRINE"
     21 "Ventilated Improved Pit latrine (VIP)"
     22 "Pit latrine with slab"
     23 "Pit latrine without slab/open pit"
     30 "NO FACILITY"
     31 "No facility/bush/field"
     41 "Composting toilet"
     42 "Bucket toilet"
     43 "Hanging toilet/latrine"
     96 "Other"
     97 "Not a dejure resident"
  /V119    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V120    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V121    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V122    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V123    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V124    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V125    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V127    
     10 "NATURAL"
     11 "Earth, sand"
     12 "Dung"
     20 "RUDIMENTARY"
     21 "Wood planks"
     22 "Palm, bamboo"
     30 "FINISHED"
     31 "Parquet, polished wood"
     32 "Vinyl, asphalt strips"
     33 "Ceramic tiles"
     34 "Cement"
     35 "Carpet"
     96 "Other"
     97 "Not a dejure resident"
  /V128    
     10 "NATURAL"
     11 "No walls"
     12 "Cane / palm / trunks"
     13 "Dirt"
     20 "RUDIMENTARY"
     21 "Bamboo with mud"
     22 "Stone with mud"
     23 "Uncovered adobe"
     24 "Metalic sheets"
     25 "Plywood"
     26 "Cardboard"
     27 "Reused wood"
     30 "FINISHED"
     31 "Cement"
     32 "Stone with lime / cement"
     33 "Bricks"
     34 "Cement blocks"
     35 "Covered adobe"
     36 "Wood planks / shingles"
     96 "Other"
     97 "Not a dejure resident"
  /V129    
     10 "NATURAL"
     11 "No roof"
     12 "Thatch / palm leaf"
     13 "Sod"
     20 "RUDIMENTARY"
     21 "Rustic mat"
     22 "Palm / bamboo"
     23 "Wood planks"
     24 "Cardboard"
     25 "Canvas/plastic sheeting"
     30 "FINISHED"
     31 "Metal sheets"
     32 "Wood"
     33 "Calamine / cement fiber"
     34 "Ceramic tiles"
     35 "Cement"
     36 "Roofing shingles"
     37 "Asbestos"
     96 "Other"
     97 "Not a dejure resident"
  /V130    
      1 "Religion 1"
      2 "Religion 2"
      3 "Religion 3"
      4 "Religion 4"
     95 "No religion"
     96 "Other"
  /V131    
      1 "Ethnic group 1"
      2 "Ethnic group 2"
      3 "Ethnic group 3"
      4 "Ethnic group 4"
      5 "Ethnic group 5"
    995 "Foreign"
    996 "Other"
  /V133    
     97 "Inconsistent"
  /V134    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /V135    
      1 "Usual resident"
      2 "Visitor"
  /V139    
      0 "Abroad"
      1 "Region 1"
      2 "Region 2"
      3 "Region 3"
      4 "Region 4"
     97 "Not dejure resident"
  /V140    
      0 "Abroad"
      1 "Urban"
      2 "Rural"
      7 "Not a dejure resident"
  /V141    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
      7 "Not a dejure resident"
  /V149    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
  /V150    
      1 "Head"
      2 "Wife"
      3 "Daughter"
      4 "Daughter-in-law"
      5 "Granddaughter"
      6 "Mother"
      7 "Mother-in-law"
      8 "Sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     98 "Don't know"
  /V151    
      1 "Male"
      2 "Female"
  /V152    
     95 "95+"
     98 "Don't know"
  /V153    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V155    
      0 "Cannot read at all"
      1 "Able to read only parts of sentence"
      2 "Able to read whole sentence"
      3 "No card with required language"
      4 "Blind/visually impaired"
  /V156    
      0 "No"
      1 "Yes"
  /V157    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V158    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V159    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V160    
      0 "No"
      1 "Yes"
      7 "Not a dejure resident"
  /V161    
      1 "Electricity"
      2 "LPG"
      3 "Natural gas"
      4 "Biogas"
      5 "Kerosene"
      6 "Coal, lignite"
      7 "Charcoal"
      8 "Wood"
      9 "Straw/shrubs/grass"
     10 "Agricultural crop"
     11 "Animal dung"
     95 "No food cooked in house"
     96 "Other"
     97 "Not a dejure resident"
  /V166    
      0 "0 ppm (no iodine)"
      7 "7 ppm"
     15 "15 ppm"
     30 "30 ppm"
    994 "Salt not tested"
    995 "No salt"
    997 "Not a dejure resident"
  /V167    
      0 "None"
     95 "95+"
  /V168    
      0 "No"
      1 "Yes"
  /V190    
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /ML101   
      0 "No net"
      1 "Only treated nets"
      2 "Both treated and untreated nets"
      3 "Only untreated nets"
  /V208    
      0 "No births"
  /V209    
      0 "No births"
  /V213    
      0 "No or unsure"
      1 "Yes"
  /V215    
    100 "Day of interview"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
    994 "In menopause/had hysterectomy"
    995 "Before last birth"
    996 "Never menstruated"
    997 "Inconsistent"
    998 "Don't know"
  /V216    
      0 "No"
      1 "Yes"
  /V217    
      1 "During her period"
      2 "After period ended"
      3 "Middle of the cycle"
      4 "Before period begins"
      5 "At any time"
      6 "Other"
      8 "Don't know"
  /V220    
      6 "6+"
  /V221    
    996 "Negative interval"
  /V223    
      7 "Month - exact date"
      8 "None - date placed"
  /V225    
      1 "Then"
      2 "Later"
      3 "Not at all"
  /V226    
    994 "In menopause"
    995 "Before last birth"
    996 "Never menstruated"
    997 "Inconsistent"
    998 "Don't know"
  /V227    
      0 "No flag"
      1 "N > interval since birth"
      2 "N + amen. > interval"
      3 "N, but period not returned"
      4 "95, but no birth"
      5 "95, but period returned"
      6 "96, but period returned"
      7 "N, last period during pregnancy"
      8 "96, had children"
      9 "N, period before last birth"
  /V228    
      0 "No"
      1 "Yes"
  /V229    
     97 "Inconsistent"
     98 "Don't know"
  /V230    
   9997 "Inconsistent"
   9998 "Don't know"
  /V231    
   9997 "Inconsistent"
   9998 "Don't know"
  /V232    
      1 "Month and year"
      2 "From calendar"
      5 "Year"
      7 "Month"
      8 "None"
  /V233    
     97 "Inconsistent"
     98 "Don't know"
  /V234    
      0 "No"
      1 "Yes"
  /V235    
      0 "No prior child"
  /V237    
      0 "No"
      1 "Yes"
  /V239    
      0 "No"
      1 "Yes"
  /V240    
     97 "Inconsistent"
     98 "Don't know"
  /V241    
   9997 "Inconsistent"
   9998 "Don't know"
  /V242    
   9997 "Inconsistent"
   9998 "Don't know"
  /V243    
      1 "Month and year"
      2 "From calendar"
      5 "Year"
      7 "Month"
      8 "None"
  /V311    
      4 "4+"
      5 "Never used"
  /V312    
      0 "Not using"
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female sterilization"
      7 "Male sterilization"
      8 "Periodic abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Implants/Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea (LAM)"
     14 "Female condom"
     15 "Foam or jelly"
     17 "Other modern method"
     18 "Specific method 1"
     19 "Specific method 2"
     20 "Specific method 3"
  /V313    
      0 "No method"
      1 "Folkloric method"
      2 "Traditional method"
      3 "Modern method"
  /V318    
      1 "Month and year - information complete"
      5 "Year - month imputed, age calculated"
      7 "Month - date placed"
      8 "None - date placed"
      9 "From calendar"
  /V319    
      1 "<2"
      2 "2-3"
      3 "4-5"
      4 "6-7"
      5 "8-9"
      6 "10+"
  /V320    
      1 "<25"
      2 "25-29"
      3 "30-34"
      4 "35-39"
      5 "40-44"
      6 "45-49"
  /V321    
      0 "Single, before marriage"
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25+"
  /V322    
      5 "5+"
  /V323    
     11 "Brand 1"
     12 "Brand 2"
     96 "Other"
     98 "Don't know"
  /V323A   
      1 "Brand 1"
      2 "Brand 2"
      3 "Brand 3"
     96 "Other"
     98 "Don't know"
  /V325A   
   9999995 "Free"
   9999998 "Don't know"
  /V326    
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Family planning clinic"
     14 "Public mobile clinic"
     15 "Public health worker"
     16 "Other public"
     20 "PRIVATE SECTOR"
     21 "Private hospital, clinic"
     22 "Pharmacy"
     23 "Private doctor's office"
     24 "Private mobile clinic"
     25 "Private health worker"
     26 "Other private medical"
     30 "OTHER SOURCE"
     31 "Shop"
     32 "Church/mosque"
     33 "Friend Relative"
     96 "Other"
     98 "Don't know"
  /V327    
      1 "Government clinic/pharmacy"
      2 "Government home/community delivery"
      3 "NGO"
      4 "Private clinic/delivery"
      5 "Pharmacy"
      6 "Shop, church, friend"
      7 "Other"
      8 "Don't know"
  /V337    
     95 "All calendar {A core}"
     96 "96+ {B core}"
    997 "Inconsistent"
    998 "Don't know"
  /V359    
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female sterilization"
      7 "Male sterilization"
      8 "Periodic abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea"
     14 "Female condom"
     15 "Foam or jelly"
     17 "Other modern method"
     18 "Specific method 2"
     19 "Specific method 3"
     20 "Specific method 4"
  /V360    
      1 "Became pregnant"
      2 "Wanted to become pregnant"
      3 "Husband disapproved"
      4 "Side effects"
      5 "Health concerns"
      6 "Access, availability"
      7 "Wanted more effective method"
      8 "Inconvenient to use"
      9 "Infrequent sex, husband away"
     10 "Cost"
     11 "Fatalistic"
     12 "Difficult pregnancy, menopause"
     13 "Marital dissolution"
     14 "Other"
     98 "Don't know"
  /V361    
      1 "Currently using"
      2 "Used since last birth"
      3 "Used before last birth"
      4 "Never used"
  /V362    
      1 "In next 12 months"
      2 "Use later"
      3 "Unsure about timing"
      4 "Unsure about use"
      5 "Does not intend"
      6 "Never had sex"
  /V363    
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female sterilization"
      7 "Male sterilization"
      8 "Periodic abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea"
     14 "Female condom"
     15 "Foam or jelly"
     17 "Specific method 1"
     18 "Specific method 2"
     19 "Specific method 3"
     20 "Specific method 4"
     98 "Don't know"
  /V364    
      1 "Using modern method"
      2 "Using traditional method"
      3 "Non-user - intends to use later"
      4 "Does not intend to use"
      5 "Never had sex"
  /V367    
      1 "Wanted then"
      2 "Wanted later"
      3 "Wanted no more"
  /V372    
      0 "Package not seen"
      1 "Package seen"
  /V372A   
      0 "Package not seen"
      1 "Package seen"
  /V375A   
     11 "Not married"
     20 "FERTILITY-RELATED"
     21 "Not having sex"
     22 "Infrequent sex"
     23 "Menopausal, hysterectomy"
     24 "Subfecund, infecund"
     25 "Postpartum, breastfeeding"
     26 "Wants more children"
     27 "Pregnant"
     30 "OPPOSITION TO USE"
     31 "Respondent opposed"
     32 "Husband opposed"
     33 "Others opposed"
     34 "Religious prohibition"
     40 "LACK OF KNOWLEDGE"
     41 "Knows no method"
     42 "Knows no source"
     50 "METHOD-RELATED"
     51 "Health concerns"
     52 "Fears side effects"
     53 "Lack of access"
     54 "Cost too much"
     55 "Inconvenient to use"
     56 "Interferes with body"
     96 "Other"
     98 "Don't know"
  /V376    
     11 "Not married"
     20 "FERTILITY-RELATED"
     22 "Infrequent sex"
     23 "Menopausal, hysterectomy"
     24 "Subfecund, infecund"
     26 "Wants more children"
     30 "OPPOSITION TO USE"
     31 "Respondent opposed"
     32 "Husband opposed"
     33 "Others opposed"
     34 "Religious prohibition"
     40 "LACK OF KNOWLEDGE"
     41 "Knows no method"
     42 "Knows no source"
     50 "METHOD-RELATED"
     51 "Health concerns"
     52 "Fears side effects"
     53 "Lack of access"
     54 "Cost too much"
     55 "Inconvenient to use"
     56 "Interferes with body"
     96 "Other"
     98 "Don't know"
  /V376A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V379    
     10 "PUBLIC SECTOR"
     20 "PRIVATE SECTOR"
     30 "OTHER SOURCE"
     96 "Other"
     98 "Don't know"
  /V380    
      1 "Government clinic/pharmacy"
      2 "Government home/community delivery"
      3 "NGO"
      4 "Private clinic/delivery"
      5 "Pharmacy"
      6 "Shop, church, friend"
      7 "Other"
      8 "Don't know"
  /V384A   
      0 "No"
      1 "Yes"
  /V384B   
      0 "No"
      1 "Yes"
  /V384C   
      0 "No"
      1 "Yes"
  /V393    
      0 "No"
      1 "Yes"
  /V394    
      0 "No"
      1 "Yes"
  /V395    
      0 "No"
      1 "Yes"
  /V3A00A  
      0 "No"
      1 "Yes"
  /V3A00B  
      0 "No"
      1 "Yes"
  /V3A00C  
      0 "No"
      1 "Yes"
  /V3A00D  
      0 "No"
      1 "Yes"
  /V3A00E  
      0 "No"
      1 "Yes"
  /V3A00F  
      0 "No"
      1 "Yes"
  /V3A00G  
      0 "No"
      1 "Yes"
  /V3A00H  
      0 "No"
      1 "Yes"
  /V3A00I  
      0 "No"
      1 "Yes"
  /V3A00J  
      0 "No"
      1 "Yes"
  /V3A00K  
      0 "No"
      1 "Yes"
  /V3A00L  
      0 "No"
      1 "Yes"
  /V3A00M  
      0 "No"
      1 "Yes"
  /V3A00N  
      0 "No"
      1 "Yes"
  /V3A00O  
      0 "No"
      1 "Yes"
  /V3A00P  
      0 "No"
      1 "Yes"
  /V3A00Q  
      0 "No"
      1 "Yes"
  /V3A00R  
      0 "No"
      1 "Yes"
  /V3A00S  
      0 "No"
      1 "Yes"
  /V3A00T  
      0 "No"
      1 "Yes"
  /V3A00U  
      0 "No"
      1 "Yes"
  /V3A00V  
      0 "No"
      1 "Yes"
  /V3A00W  
      0 "No"
      1 "Yes"
  /V3A00X  
      0 "No"
      1 "Yes"
  /V3A00Y  
      0 "No: knows a source"
      1 "Yes: knows no source"
  /V3A00Z  
      0 "No"
      1 "Yes"
  /V3A01   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V3A02   
      0 "No"
      1 "Yes"
  /V3A03   
      0 "No"
      1 "Yes"
  /V3A04   
      0 "No"
      1 "Yes"
  /V3A05   
      0 "No"
      1 "Yes"
  /V3A06   
      0 "No"
      1 "Yes"
  /V3A07   
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Family planning clinic"
     14 "Public mobile clinic"
     15 "Public health worker"
     16 "Other public"
     20 "PRIVATE SECTOR"
     21 "Private hospital, clinic"
     22 "Pharmacy"
     23 "Private doctor's office"
     24 "Private mobile clinic"
     25 "Private health worker"
     26 "Other private medical"
     30 "OTHER SOURCE"
     31 "Shop"
     32 "Church/mosque"
     33 "Friend Relative"
     96 "Other"
     98 "Don't know"
  /V3A08A  
      0 "No"
      1 "Yes"
  /V3A08B  
      0 "No"
      1 "Yes"
  /V3A08C  
      0 "No"
      1 "Yes"
  /V3A08D  
      0 "No"
      1 "Yes"
  /V3A08E  
      0 "No"
      1 "Yes"
  /V3A08F  
      0 "No"
      1 "Yes"
  /V3A08G  
      0 "No"
      1 "Yes"
  /V3A08H  
      0 "No"
      1 "Yes"
  /V3A08I  
      0 "No"
      1 "Yes"
  /V3A08J  
      0 "No"
      1 "Yes"
  /V3A08K  
      0 "No"
      1 "Yes"
  /V3A08L  
      0 "No"
      1 "Yes"
  /V3A08M  
      0 "No"
      1 "Yes"
  /V3A08N  
      0 "No"
      1 "Yes"
  /V3A08O  
      0 "No"
      1 "Yes"
  /V3A08P  
      0 "No"
      1 "Yes"
  /V3A08Q  
      0 "No"
      1 "Yes"
  /V3A08R  
      0 "No"
      1 "Yes"
  /V3A08S  
      0 "No"
      1 "Yes"
  /V3A08T  
      0 "No"
      1 "Yes"
  /V3A08U  
      0 "No"
      1 "Yes"
  /V3A08V  
      0 "No"
      1 "Yes"
  /V3A08W  
      0 "No"
      1 "Yes"
  /V3A08AA 
      0 "No"
      1 "Yes"
  /V3A08AB 
      0 "No"
      1 "Yes"
  /V3A08AC 
      0 "No"
      1 "Yes"
  /V3A08AD 
      0 "No"
      1 "Yes"
  /V3A08X  
      0 "No"
      1 "Yes"
  /V3A08Z  
      0 "No"
      1 "Yes: don't know"
  /V3A09A  
    998 "Don't know"
  /V3A09B  
    998 "Don't know"
  /V401    
      0 "No"
      1 "Yes"
  /V404    
      0 "No"
      1 "Yes"
  /V405    
      0 "No"
      1 "Yes"
  /V406    
      0 "No"
      1 "Yes"
  /V407    
     96 "On demand"
  /V408    
     96 "On demand"
  /V409    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V409A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V410    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V410A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V411    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V411A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V412    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V412A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V412B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V412C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414H   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414I   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414J   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414K   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414L   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414M   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414N   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414O   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414P   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414Q   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414R   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414S   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414T   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414U   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414V   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414W   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V415    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V416    
      0 "Never heard of"
      1 "Used ORS"
      2 "Heard of ORS"
  /V426    
      0 "Immediately"
    100 "Within first hour"
    101 "Hours: 1"
    199 "Hours: number missing"
    201 "Days: 1"
    299 "Days: number missing"
  /V437    
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /V438    
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /V439    
   9998 "Flagged cases"
  /V440    
   9998 "Flagged cases"
  /V441    
   99998 "Flagged cases"
  /V442    
   99998 "Flagged cases"
  /V443    
   99998 "Flagged cases"
  /V444    
   99998 "Flagged cases"
  /V444A   
   9998 "Flagged cases"
  /V445    
   9998 "Flagged cases"
  /V446    
   9998 "Flagged cases"
  /V447    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
      7 "No measurement found in household"
  /V452A   
      1 "Under age 18"
      2 "Age 18 or older"
  /V452B   
      0 "Not in household"
  /V452C   
      1 "Granted"
      2 "Parent/other refused"
      3 "Respondent refused"
  /V453    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /V454    
      0 "No/don't know"
      1 "Yes"
  /V455    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
      7 "No measurement found in household"
  /V456    
    997 "Inconsistent"
  /V457    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /V458    
      0 "No"
      1 "Yes"
  /V459    
      0 "No"
      1 "Yes"
  /V460    
      0 "No"
      1 "All children"
      2 "Some children"
      3 "No net in household"
  /V461    
      0 "No"
      1 "Yes"
  /V462    
      0 "No"
      1 "Yes"
      2 "Never prepared meal"
  /V463A   
      0 "No"
      1 "Yes"
  /V463B   
      0 "No"
      1 "Yes"
  /V463C   
      0 "No"
      1 "Yes"
  /V463D   
      0 "No"
      1 "Yes"
  /V463E   
      0 "No"
      1 "Yes"
  /V463F   
      0 "No"
      1 "Yes"
  /V463G   
      0 "No"
      1 "Yes"
  /V463X   
      0 "No"
      1 "Yes"
  /V463Z   
      0 "No"
      1 "Yes, smokes nothing"
  /V464    
     80 "80+"
     98 "Don't know"
  /V465    
      1 "Used toilet/latrine"
      2 "Put/rinsed in toilet/latrine"
      3 "Put/rinsed into drain or ditch"
      4 "Throw into garbage"
      5 "Buried"
      6 "Rinse away"
      7 "Use disposable diapers"
      8 "Use washable diapers"
      9 "Left in the open/not disposed of"
     96 "Other"
  /V466    
      0 "No"
      1 "Yes"
      2 "Depends"
  /V467A   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467B   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467C   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467D   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467E   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467F   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467G   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467H   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467I   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467J   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467K   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467L   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467M   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V468    
      0 "See specific questions"
      1 "Last birth only"
      2 "All births in last 5 years"
  /V469E   
      0 "No"
      7 "7+"
      8 "DK"
  /V469F   
      0 "No"
      7 "7+"
      8 "DK"
  /V469X   
      0 "No"
      7 "7+"
      8 "DK"
  /V471A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472H   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472I   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472J   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472K   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472L   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472M   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472N   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472O   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472P   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472Q   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472R   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472S   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472T   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472U   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V473A   
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Sample not tested/lost/not enough DBS"
  /V473B   
      1 "Blood taken"
      2 "Not present"
      3 "Refused"
      4 "Sample not tested/lost/damaged/insufficient"
      5 "Not enough DBS to complete protocol"
      6 "Other"
  /V474    
      0 "No"
      1 "Yes"
  /V474A   
      0 "No"
      1 "Yes"
  /V474B   
      0 "No"
      1 "Yes"
  /V474C   
      0 "No"
      1 "Yes"
  /V474D   
      0 "No"
      1 "Yes"
  /V474E   
      0 "No"
      1 "Yes"
  /V474F   
      0 "No"
      1 "Yes"
  /V474G   
      0 "No"
      1 "Yes"
  /V474H   
      0 "No"
      1 "Yes"
  /V474I   
      0 "No"
      1 "Yes"
  /V474J   
      0 "No"
      1 "Yes"
  /V474X   
      0 "No"
      1 "Yes"
  /V474Z   
      0 "No"
      1 "Yes"
  /V475    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V476    
      0 "No"
      1 "Yes, remain a secret"
      8 "Don't know/not sure/depends"
  /V477    
      0 "None"
     90 "90+"
     98 "Don't know"
  /V478    
      0 "None"
     90 "90+"
     98 "Don't know"
  /V479    
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     16 "Other public sector"
     20 "PRIVATE SECTOR"
     21 "Private hospital/clinic/doctor"
     22 "Dental clinic/office"
     23 "Pharmacy"
     24 "Office or home of nurse/health worker"
     26 "Other private sector"
     30 "OTHER NON-MEDICAL"
     31 "Respondent's home"
     96 "Other"
  /V480    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V481    
      0 "No"
      1 "Yes"
  /V481A   
      0 "No"
      1 "Yes"
  /V481B   
      0 "No"
      1 "Yes"
  /V481C   
      0 "No"
      1 "Yes"
  /V481D   
      0 "No"
      1 "Yes"
  /V481E   
      0 "No"
      1 "Yes"
  /V481F   
      0 "No"
      1 "Yes"
  /V481G   
      0 "No"
      1 "Yes"
  /V481H   
      0 "No"
      1 "Yes"
  /V481X   
      0 "No"
      1 "Yes"
  /V482A   
      0 "No"
      1 "Yes"
      8 "Unsure"
  /V482B   
      0 "No"
      1 "Yes"
  /V482C   
      0 "No"
      1 "Yes"
      8 "Unsure"
  /V501    
      0 "Never in union"
      1 "Married"
      2 "Living with partner"
      3 "Widowed"
      4 "Divorced"
      5 "No longer living together/separated"
  /V502    
      0 "Never in union"
      1 "Currently in union/living with a man"
      2 "Formerly in union/living with a man"
  /V503    
      1 "Once"
      2 "More than once"
  /V504    
      1 "Living with her"
      2 "Staying elsewhere"
  /V505    
      0 "No other wives"
     98 "Don't know"
  /V506    
     98 "Don't know"
  /V510    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /V513    
      0 "Never married"
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25-29"
      7 "30+"
  /V525    
      0 "Not had sex"
     96 "At first union"
     97 "Inconsistent"
     98 "Don't know"
  /V527    
    100 "<1 day ago"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /V528    
     31 "31+ days"
     95 "Within last 4 weeks"
     96 "Before last birth"
     97 "Inconsistent"
     98 "Don't know"
  /V529    
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /V530    
      0 "No flag"
      1 "N > interval since birth"
      2 "N + abstinence > interval"
      3 "N, but sex not res."
      4 "96, but no birth"
      5 "96, but currently pregnant"
      6 "96, but resumed sex"
      7 "N, last sex before pregnancy"
      8 "N, inconsistent 4 weeks"
      9 "N, sex before last birth"
  /V531    
      0 "Not had sex"
     97 "Inconsistent"
     98 "Don't know"
  /V532    
      0 "No flag"
      1 "After interview"
      2 "After conception >= 1 year"
      3 "After conception < 1 year"
      4 "At marriage, but never married"
      5 "At marriage, but after conception"
      6 "After marriage"
  /V535    
      0 "No"
      1 "Formerly married"
      2 "Lived with a man"
  /V536    
      0 "Never had sex"
      1 "Active in last 4 weeks"
      2 "Not active in last 4 weeks - postpartum abstinence"
      3 "Not active in last 4 weeks - not postpartum abstinence"
  /V537    
     60 "60+"
     96 "Before last birth"
     97 "Inconsistent"
     98 "Don't know"
  /V538    
      1 "Death/widowhood"
      2 "Divorce"
      3 "Separation"
  /V539    
      1 "Respondent"
      2 "Other wife"
      3 "Spouse's children"
      4 "Spouse's family"
      6 "Other"
      7 "No property"
  /V540    
      0 "No"
      1 "Yes"
  /V541    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V602    
      1 "Have another"
      2 "Undecided"
      3 "No more"
      4 "Sterilized (respondent or partner)"
      5 "Declared infecund"
      6 "Never had sex"
  /V603    
    100 "Wanted now"
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    993 "After marriage"
    994 "Soon, now"
    996 "Other, non-numeric"
    997 "Inconsistent"
    998 "Don't know"
  /V604    
      0 "<12 months"
      1 "1 year"
      2 "2 years"
      3 "3 years"
      4 "4 years"
      5 "5 years"
      6 "6+ years"
      7 "Non-numeric"
      8 "Don't know"
  /V605    
      1 "Wants within 2 years"
      2 "Wants after 2+ years"
      3 "Wants, unsure timing"
      4 "Undecided"
      5 "Wants no more"
      6 "Sterilized (respondent or partner)"
      7 "Declared infecund"
      8 "Never had sex"
  /V613    
     96 "Non-numeric response"
     98 "Don't know"
  /V614    
      6 "6+"
      7 "Non-numeric response"
  /V616    
    100 "Wanted now"
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    993 "After marriage"
    994 "Soon/now"
    995 "Can't get pregnant"
    996 "Other"
    998 "Don't know"
  /V621    
      1 "Both want same"
      2 "Husband wants more"
      3 "Husband wants fewer"
      8 "Don't know"
  /V623    
      0 "Fecund"
      1 "Pregnant"
      2 "Postpartum amenorrheic"
      3 "Infecund, menopausal"
  /V624    
      0 "Never had sex"
      1 "Unmet need for spacing"
      2 "Unmet need for limiting"
      3 "Using for spacing"
      4 "Using for limiting"
      5 "Spacing failure"
      6 "Limiting failure"
      7 "No unmet need"
      8 "Not married and no sex in last 30 days"
      9 "Infecund, menopausal"
  /V625    
      0 "Fecund"
      1 "Pregnant"
      2 "Postpartum amenorrheic"
      3 "Infecund, menopausal"
  /V626    
      0 "Never had sex"
      1 "Unmet need for spacing"
      2 "Unmet need for limiting"
      3 "Using for spacing"
      4 "Using for limiting"
      5 "Spacing failure"
      6 "Limiting failure"
      7 "No unmet need"
      8 "Not married and no sex in last 30 days"
      9 "Infecund, menopausal"
  /V625A   
      0 "Fecund"
      1 "Pregnant"
      2 "Postpartum amenorrheic"
      3 "Infecund, menopausal"
  /V626A   
      0 "Never had sex"
      1 "Unmet need for spacing"
      2 "Unmet need for limiting"
      3 "Using for spacing"
      4 "Using for limiting"
      7 "No unmet need"
      8 "Not married and no sex in last 30 days"
      9 "Infecund, menopausal"
  /V627    
     96 "Other"
     98 "Don't know"
  /V628    
     96 "Other"
     98 "Don't know"
  /V629    
     96 "Other"
     98 "Don't know"
  /V631    
      1 "Big problem"
      2 "Small problem"
      3 "No problem"
      4 "Says she can't get pregnant/not having sex"
  /V632    
      1 "Mainly respondent"
      2 "Mainly husband, partner"
      3 "Joint decision"
      6 "Other"
  /V633A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V634    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V701    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /V702    
      0 "No years completed at level V702"
     98 "Don't know"
  /V704    
      0 "Did not work"
      1 "Armed forces"
     11 "Legislators and senior officials"
     12 "Corporate managers"
     13 "General managers"
     21 "Physical, mathematical and engineering science professionals"
     22 "Life science and health professional"
     23 "Teaching professionals"
     24 "Other professionals"
     31 "Physical and engineering science associate professionals"
     32 "Life science and health associate professionals"
     33 "Teaching associate professionals"
     34 "Other associate professionals"
     41 "Office clerks"
     42 "Customer service clerks"
     51 "Personal and protective services workers"
     52 "Models, salespersons and demonstrators"
     61 "Market-oriented skilled agricultural and fishery workers"
     62 "Subsistence agricultural and fishery workers"
     71 "Extraction and building trade workers"
     72 "Metal, machinery and related trades workers"
     73 "Precision, handicraft, printing and related trades workers"
     74 "Other craft and related trades workers"
     81 "Stationary plant and related operators"
     82 "Machine operators and assemblers"
     83 "Drivers and mobile plant operators"
     91 "Sales and services elementary occupations"
     92 "Agricultural, fishery and related labourers"
     93 "Labourers in mining, construction, manufacturing and transport"
     96 "Other"
  /V705    
      0 "Did not work"
      1 "Professional/technical/managerial"
      2 "Clerical"
      3 "Sales"
      4 "Agricultural - self employed"
      5 "Agricultural - employee"
      6 "Household and domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     96 "Other"
     98 "Don't know"
  /V714    
      0 "No"
      1 "Yes"
  /V714A   
      0 "No"
      1 "Yes"
  /V715    
     97 "Inconsistent"
     98 "Don't know"
  /V716    
      0 "Not working"
      1 "Armed forces"
     11 "Legislators and senior officials"
     12 "Corporate managers"
     13 "General managers"
     21 "Physical, mathematical and engineering science professionals"
     22 "Life science and health professional"
     23 "Teaching professionals"
     24 "Other professionals"
     31 "Physical and engineering science associate professionals"
     32 "Life science and health associate professionals"
     33 "Teaching associate professionals"
     34 "Other associate professionals"
     41 "Office clerks"
     42 "Customer service clerks"
     51 "Personal and protective services workers"
     52 "Models, salespersons and demonstrators"
     61 "Market-oriented skilled agricultural and fishery workers"
     62 "Subsistence agricultural and fishery workers"
     71 "Extraction and building trade workers"
     72 "Metal, machinery and related trades workers"
     73 "Precision, handicraft, printing and related trades workers"
     74 "Other craft and related trades workers"
     81 "Stationary plant and related operators"
     82 "Machine operators and assemblers"
     83 "Drivers and mobile plant operators"
     91 "Sales and services elementary occupations"
     92 "Agricultural, fishery and related labourers"
     93 "Labourers in mining, construction, manufacturing and transport"
     95 "Housework"
     96 "Other"
  /V717    
      0 "Not working"
      1 "Professional/technical/managerial"
      2 "Clerical"
      3 "Sales"
      4 "Agricultural - self employed"
      5 "Agricultural - employee"
      6 "Household and domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     96 "Other"
     98 "Don't know"
  /V719    
      1 "For family member"
      2 "For someone else"
      3 "Self-employed"
  /V721    
      1 "At home"
      2 "Away"
  /V729    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      8 "Don't know"
  /V730    
     95 "95+"
     98 "Don't know"
  /V731    
      0 "No"
      1 "In the past year"
      2 "Currently working"
      3 "Have a job, but on leave last 7 days"
  /V732    
      1 "All year"
      2 "Seasonal"
      3 "Occasional"
  /V739    
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
  /V740    
      0 "Own land"
      1 "Family land"
      2 "Someone else's land"
      3 "Rented land"
      8 "Don't know"
  /V741    
      0 "Not paid"
      1 "Cash only"
      2 "Cash and in-kind"
      3 "In-kind only"
  /V743A   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743B   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743C   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743D   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743E   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743F   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
      7 "Husband/partner has no earnings"
  /V744A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V744B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V744C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V744D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V744E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V745A   
      0 "Does not own"
      1 "Alone only"
      2 "Jointly only"
      3 "Both alone and jointly"
  /V745B   
      0 "Does not own"
      1 "Alone only"
      2 "Jointly only"
      3 "Both alone and jointly"
  /V746    
      1 "More than him"
      2 "Less than him"
      3 "About the same"
      4 "Husband/partner doesn't bring in money"
      8 "Don't know"
  /B0      
      0 "Single birth"
      1 "1st of multiple"
      2 "2nd of multiple"
      3 "3rd of multiple"
      4 "4th of multiple"
      5 "5th of multiple"
  /B4      
      1 "Male"
      2 "Female"
  /B5      
      0 "No"
      1 "Yes"
  /B6      
    100 "Died on day of birth"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Months: 1"
    299 "Months: number missing"
    301 "Years: 1"
    399 "Years: number missing"
    997 "Inconsistent"
    998 "Don't know"
  /B9      
      0 "Respondent"
      1 "Father"
      2 "Other relative"
      3 "Someone else"
      4 "Lives elsewhere"
  /B10     
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /B13     
      0 "No flag"
      1 "> interview"
      2 "< breastfeeding"
      3 "< age supplemented"
      4 "< first breastfed"
      5 "< last vaccination"
      6 "Outside range"
      7 "Imputed, units given"
      8 "Imputed, no units"
  /B15     
      0 "No"
      1 "Yes"
  /B16     
      0 "Not listed in household"
  /M1      
      0 "Received no injection"
      7 "7+"
      8 "Don't know"
  /M1A     
      0 "Received no injection"
      7 "7+"
      8 "Don't know"
  /M1B     
     97 "Inconsistent"
     98 "Don't know month"
  /M1C     
   9997 "Inconsistent"
   9998 "Don't know year"
  /M1E     
   9996 "Can't be determined"
  /M2A     
      0 "No"
      1 "Yes"
  /M2B     
      0 "No"
      1 "Yes"
  /M2C     
      0 "No"
      1 "Yes"
  /M2D     
      0 "No"
      1 "Yes"
  /M2E     
      0 "No"
      1 "Yes"
  /M2F     
      0 "No"
      1 "Yes"
  /M2G     
      0 "No"
      1 "Yes"
  /M2H     
      0 "No"
      1 "Yes"
  /M2I     
      0 "No"
      1 "Yes"
  /M2J     
      0 "No"
      1 "Yes"
  /M2K     
      0 "No"
      1 "Yes"
  /M2L     
      0 "No"
      1 "Yes"
  /M2M     
      0 "No"
      1 "Yes"
  /M2N     
      0 "No: some care"
      1 "Yes: no care"
  /M3A     
      0 "No"
      1 "Yes"
  /M3B     
      0 "No"
      1 "Yes"
  /M3C     
      0 "No"
      1 "Yes"
  /M3D     
      0 "No"
      1 "Yes"
  /M3E     
      0 "No"
      1 "Yes"
  /M3F     
      0 "No"
      1 "Yes"
  /M3G     
      0 "No"
      1 "Yes"
  /M3H     
      0 "No"
      1 "Yes"
  /M3I     
      0 "No"
      1 "Yes"
  /M3J     
      0 "No"
      1 "Yes"
  /M3K     
      0 "No"
      1 "Yes"
  /M3L     
      0 "No"
      1 "Yes"
  /M3M     
      0 "No"
      1 "Yes"
  /M3N     
      0 "No: some assistance"
      1 "Yes: no assistance"
  /M4      
     93 "Ever breastfed, not currently breastfeeding"
     94 "Never breastfed"
     95 "Still breastfeeding"
     96 "Breastfed until died"
     97 "Inconsistent"
     98 "Don't know"
  /M5      
     93 "Ever breastfed, not currently breastfeeding"
     94 "Never breastfed"
     97 "Inconsistent"
     98 "Don't know"
  /M6      
     96 "Period not returned"
     97 "Inconsistent"
     98 "Don't know"
  /M7      
     97 "Inconsistent"
     98 "Don't know"
  /M8      
     96 "Still abstaining"
     97 "Inconsistent"
     98 "Don't know"
  /M9      
     97 "Inconsistent"
     98 "Don't know"
  /M10     
      1 "Then"
      2 "Later"
      3 "No more"
  /M11     
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    998 "Don't know"
  /M13     
     98 "Don't know"
  /M14     
      0 "No antenatal visits"
     98 "Don't know"
  /M15     
     10 "HOME"
     11 "Respondent's home"
     12 "Other home"
     20 "PUBLIC SECTOR"
     21 "Government hospital"
     22 "Government health center"
     23 "Government health post"
     26 "Other public sector"
     30 "PRIVATE SECTOR"
     31 "Private hospital/clinic"
     36 "Other private sector"
     96 "Other"
  /M17     
      0 "No"
      1 "Yes"
  /M18     
      1 "Very large"
      2 "Larger than average"
      3 "Average"
      4 "Smaller than average"
      5 "Very small"
      8 "Don't know"
  /M19     
   9996 "Not weighed at birth"
   9998 "Don't know"
  /M19A    
      0 "Not weighed"
      1 "From written card"
      2 "From mother's recall"
      8 "Don't know"
      9 "Special answers"
  /M27     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 month"
      3 "> age at death"
      4 "During pregnancy in calendar"
  /M28     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 month"
      4 "During pregnancy in calendar"
  /M29     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 month"
      4 "During pregnancy in calendar"
  /M34     
      0 "Immediately"
    100 "Within first hour"
    101 "Hours: 1"
    199 "Hours: number missing"
    201 "Days: 1"
    299 "Days: number missing"
  /M35     
     96 "On demand"
  /M36     
     96 "On demand"
  /M38     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M39A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M39     
      0 "None"
      7 "7+"
      8 "Don't know"
  /M42A    
      0 "No"
      1 "Yes"
  /M42B    
      0 "No"
      1 "Yes"
  /M42C    
      0 "No"
      1 "Yes"
  /M42D    
      0 "No"
      1 "Yes"
  /M42E    
      0 "No"
      1 "Yes"
  /M43     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M44     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M45     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M46     
      0 "Were not taken"
    998 "Don't know"
  /M47     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M48     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49D    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49E    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49F    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49G    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49X    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49Z    
      0 "No"
      1 "Yes: don't know which drug taken"
      8 "Don't know"
  /M49Y    
      0 "No"
      1 "Yes, took no drug"
      8 "Don't know"
  /M50     
      0 "No"
      1 "Yes"
  /M51     
    100 "Zero hours"
    101 "1 Hours"
    199 "Hours missing"
    201 "1 Days"
    299 "Days missing"
    301 "1 Week"
    399 "Weeks missing"
    998 "Don't know"
  /M52     
     10 "HEALTH PROFESSIONAL"
     11 "Doctor"
     12 "Nurse/midwife"
     13 "Auxiliary midwife"
     20 "OTHER PERSON"
     21 "Traditional birth attendant"
     22 "Community/village health worker"
     96 "Other"
  /M54     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M55A    
      0 "No"
      1 "Yes"
  /M55B    
      0 "No"
      1 "Yes"
  /M55C    
      0 "No"
      1 "Yes"
  /M55D    
      0 "No"
      1 "Yes"
  /M55E    
      0 "No"
      1 "Yes"
  /M55F    
      0 "No"
      1 "Yes"
  /M55G    
      0 "No"
      1 "Yes"
  /M55H    
      0 "No"
      1 "Yes"
  /M55I    
      0 "No"
      1 "Yes"
  /M55J    
      0 "No"
      1 "Yes"
  /M55K    
      0 "No"
      1 "Yes"
  /M55L    
      0 "No"
      1 "Yes"
  /M55M    
      0 "No"
      1 "Yes"
  /M55N    
      0 "No"
      1 "Yes"
  /M55O    
      0 "No"
      1 "Yes"
  /M55X    
      0 "No"
      1 "Yes"
  /M55Z    
      0 "No: given something"
      1 "Yes: given nothing"
  /M57A    
      0 "No"
      1 "Yes"
  /M57B    
      0 "No"
      1 "Yes"
  /M57C    
      0 "No"
      1 "Yes"
  /M57D    
      0 "No"
      1 "Yes"
  /M57E    
      0 "No"
      1 "Yes"
  /M57F    
      0 "No"
      1 "Yes"
  /M57G    
      0 "No"
      1 "Yes"
  /M57H    
      0 "No"
      1 "Yes"
  /M57I    
      0 "No"
      1 "Yes"
  /M57J    
      0 "No"
      1 "Yes"
  /M57K    
      0 "No"
      1 "Yes"
  /M57L    
      0 "No"
      1 "Yes"
  /M57M    
      0 "No"
      1 "Yes"
  /M57N    
      0 "No"
      1 "Yes"
  /M57O    
      0 "No"
      1 "Yes"
  /M57P    
      0 "No"
      1 "Yes"
  /M57Q    
      0 "No"
      1 "Yes"
  /M57R    
      0 "No"
      1 "Yes"
  /M57S    
      0 "No"
      1 "Yes"
  /M57T    
      0 "No"
      1 "Yes"
  /M57U    
      0 "No"
      1 "Yes"
  /M57V    
      0 "No"
      1 "Yes"
  /M57X    
      0 "No"
      1 "Yes"
  /M60     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M61     
    100 "Hours: 0"
    101 "Hours: 1"
    199 "Hours: number missing"
    201 "Days: 1"
    299 "Days: number missing"
    301 "Weeks: 1"
    399 "Weeks: number missing"
    998 "Don't know"
  /M62     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M65A    
      0 "No"
      1 "Yes"
  /M65B    
      0 "No"
      1 "Yes"
  /M65C    
      0 "No"
      1 "Yes"
  /M65D    
      0 "No"
      1 "Yes"
  /M65E    
      0 "No"
      1 "Yes"
  /M65F    
      0 "No"
      1 "Yes"
  /M65G    
      0 "No"
      1 "Yes"
  /M65H    
      0 "No"
      1 "Yes"
  /M65I    
      0 "No"
      1 "Yes"
  /M65J    
      0 "No"
      1 "Yes"
  /M65K    
      0 "No"
      1 "Yes"
  /M65L    
      0 "No"
      1 "Yes"
  /M65X    
      0 "No"
      1 "Yes"
  /M66     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M70     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M71     
    100 "Immediately/in first hour"
    101 "Hours: 1"
    199 "Hours: number missing"
    201 "Days: 1"
    299 "Days: number missing"
    301 "Weeks: 1"
    399 "Weeks: number missing"
    998 "Don't know"
  /M72     
     10 "MEDICAL PERSONNEL"
     11 "Doctor"
     12 "Nurse, midwife"
     13 "Auxiliary midwife"
     20 "OTHER PERSON"
     21 "Traditional birth attendant"
     22 "Community/village health worker"
     96 "Other"
  /M73     
     10 "HOME"
     11 "Respondent's home"
     12 "Other home"
     20 "PUBLIC SECTOR"
     21 "Government hospital"
     22 "Government health center"
     23 "Government health post"
     26 "Other public sector"
     30 "PRIVATE SECTOR"
     31 "Private hospital, clinic"
     36 "Other private sector"
     96 "Other"
  /H1      
      0 "No card"
      1 "Yes, seen"
      2 "Yes, not seen"
      3 "No longer has card"
  /H2      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H2D     
     97 "Inconsistent"
     98 "Don't know"
  /H2M     
     97 "Inconsistent"
     98 "Don't know"
  /H2Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H3      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H3D     
     97 "Inconsistent"
     98 "Don't know"
  /H3M     
     97 "Inconsistent"
     98 "Don't know"
  /H3Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H4      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H4D     
     97 "Inconsistent"
     98 "Don't know"
  /H4M     
     97 "Inconsistent"
     98 "Don't know"
  /H4Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H5      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H5D     
     97 "Inconsistent"
     98 "Don't know"
  /H5M     
     97 "Inconsistent"
     98 "Don't know"
  /H5Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H6      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H6D     
     97 "Inconsistent"
     98 "Don't know"
  /H6M     
     97 "Inconsistent"
     98 "Don't know"
  /H6Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H7      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H7D     
     97 "Inconsistent"
     98 "Don't know"
  /H7M     
     97 "Inconsistent"
     98 "Don't know"
  /H7Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H8      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H8D     
     97 "Inconsistent"
     98 "Don't know"
  /H8M     
     97 "Inconsistent"
     98 "Don't know"
  /H8Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H9      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H9D     
     97 "Inconsistent"
     98 "Don't know"
  /H9M     
     97 "Inconsistent"
     98 "Don't know"
  /H9Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H0      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H0D     
     97 "Inconsistent"
     98 "Don't know"
  /H0M     
     97 "Inconsistent"
     98 "Don't know"
  /H0Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H10     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H11     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
  /H11B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H12A    
      0 "No"
      1 "Yes"
  /H12B    
      0 "No"
      1 "Yes"
  /H12C    
      0 "No"
      1 "Yes"
  /H12D    
      0 "No"
      1 "Yes"
  /H12E    
      0 "No"
      1 "Yes"
  /H12F    
      0 "No"
      1 "Yes"
  /H12G    
      0 "No"
      1 "Yes"
  /H12H    
      0 "No"
      1 "Yes"
  /H12I    
      0 "No"
      1 "Yes"
  /H12J    
      0 "No"
      1 "Yes"
  /H12K    
      0 "No"
      1 "Yes"
  /H12L    
      0 "No"
      1 "Yes"
  /H12M    
      0 "No"
      1 "Yes"
  /H12N    
      0 "No"
      1 "Yes"
  /H12O    
      0 "No"
      1 "Yes"
  /H12P    
      0 "No"
      1 "Yes"
  /H12Q    
      0 "No"
      1 "Yes"
  /H12R    
      0 "No"
      1 "Yes"
  /H12S    
      0 "No"
      1 "Yes"
  /H12T    
      0 "No"
      1 "Yes"
  /H12U    
      0 "No"
      1 "Yes"
  /H12V    
      0 "No"
      1 "Yes"
  /H12W    
      0 "No"
      1 "Yes"
  /H12X    
      0 "No"
      1 "Yes"
  /H12Y    
      0 "No: received treatment"
      1 "Yes: no treatment"
  /H12Z    
      0 "No"
      1 "Yes"
  /H13     
      0 "No"
      1 "Yes: ORS - spontaneous"
      2 "Yes: ORS - probed"
      8 "Don't know"
  /H13B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H14     
      0 "No"
      1 "Yes: RHS - spontaneous"
      2 "Yes: RHS - probed"
      8 "Don't know"
  /H15     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15D    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15E    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15F    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15G    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15H    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15I    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15J    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15K    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15L    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15M    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H20     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H21A    
      0 "No: received treatment"
      1 "Yes: no treatment"
      8 "Don't know"
  /H21     
      0 "No"
      1 "Yes"
  /H22     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H31     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
  /H31B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H31C    
      1 "Chest only"
      2 "Nose only"
      3 "Both"
      6 "Other"
      8 "Don't know"
  /H31D    
      0 "Nothing to drink"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /H31E    
      0 "Stopped food"
      1 "Never gave food"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /H32A    
      0 "No"
      1 "Yes"
  /H32B    
      0 "No"
      1 "Yes"
  /H32C    
      0 "No"
      1 "Yes"
  /H32D    
      0 "No"
      1 "Yes"
  /H32E    
      0 "No"
      1 "Yes"
  /H32F    
      0 "No"
      1 "Yes"
  /H32G    
      0 "No"
      1 "Yes"
  /H32H    
      0 "No"
      1 "Yes"
  /H32I    
      0 "No"
      1 "Yes"
  /H32J    
      0 "No"
      1 "Yes"
  /H32K    
      0 "No"
      1 "Yes"
  /H32L    
      0 "No"
      1 "Yes"
  /H32M    
      0 "No"
      1 "Yes"
  /H32N    
      0 "No"
      1 "Yes"
  /H32O    
      0 "No"
      1 "Yes"
  /H32P    
      0 "No"
      1 "Yes"
  /H32Q    
      0 "No"
      1 "Yes"
  /H32R    
      0 "No"
      1 "Yes"
  /H32S    
      0 "No"
      1 "Yes"
  /H32T    
      0 "No"
      1 "Yes"
  /H32U    
      0 "No"
      1 "Yes"
  /H32V    
      0 "No"
      1 "Yes"
  /H32W    
      0 "No"
      1 "Yes"
  /H32X    
      0 "No"
      1 "Yes"
  /H32Y    
      0 "No: received treatment"
      1 "Yes: no treatment"
  /H32Z    
      0 "No"
      1 "Yes"
  /H33     
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H33D    
     97 "Inconsistent"
     98 "Don't know"
  /H33M    
     97 "Inconsistent"
     98 "Don't know"
  /H33Y    
   9997 "Inconsistent"
   9998 "Don't know"
  /H34     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H35     
      0 "No"
      1 "Yes"
      2 "No vaccination in last 2 years"
      8 "Don't know"
  /H36A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36D    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36E    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36F    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H37A    
      0 "No"
      1 "Yes"
  /H37B    
      0 "No"
      1 "Yes"
  /H37C    
      0 "No"
      1 "Yes"
  /H37D    
      0 "No"
      1 "Yes"
  /H37E    
      0 "No"
      1 "Yes"
  /H37F    
      0 "No"
      1 "Yes"
  /H37G    
      0 "No"
      1 "Yes"
  /H37H    
      0 "No"
      1 "Yes"
  /H37I    
      0 "No"
      1 "Yes"
  /H37J    
      0 "No"
      1 "Yes"
  /H37K    
      0 "No"
      1 "Yes"
  /H37L    
      0 "No"
      1 "Yes"
  /H37M    
      0 "No"
      1 "Yes"
  /H37N    
      0 "No"
      1 "Yes"
  /H37O    
      0 "No"
      1 "Yes"
  /H37P    
      0 "No"
      1 "Yes"
  /H37X    
      0 "No"
      1 "Yes"
  /H37Y    
      0 "No"
      1 "Yes, nothing taken"
  /H37Z    
      0 "No"
      1 "Yes, don't know"
  /H38     
      0 "Nothing to drink"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /H39     
      0 "Stopped food"
      1 "Never gave food"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /H40     
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H40D    
     97 "Inconsistent"
     98 "Don't know"
  /H40M    
     97 "Inconsistent"
     98 "Don't know"
  /H40Y    
   9997 "Inconsistent"
   9998 "Don't know"
  /H41A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H41B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H42     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H43     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H44A    
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Government health post"
     14 "Public mobile clinic"
     15 "Public health worker"
     16 "Other public"
     20 "PRIVATE SECTOR"
     21 "Private hospital, clinic"
     22 "Pharmacy"
     23 "Private doctor"
     24 "Private mobile clinic"
     25 "Private health worker"
     26 "Other private"
     30 "OTHER"
     31 "Shop"
     32 "Traditional practitioner"
     33 "Market"
     96 "Other"
  /H44B    
      0 "Same day"
     98 "Don't know"
  /H44C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H45     
     98 "Don't know"
  /H46A    
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Government health post"
     14 "Public mobile clinic"
     15 "Public health worker"
     16 "Community health worker"
     17 "Other public"
     20 "PRIVATE SECTOR"
     21 "Private hospital, clinic"
     22 "Pharmacy"
     23 "Private doctor"
     24 "Private mobile clinic"
     25 "Private health worker"
     26 "Other private medical"
     30 "OTHER"
     31 "Shop"
     32 "Traditional practitioner"
     33 "Market"
     96 "Other"
  /H46B    
      0 "Same day"
     98 "Don't know"
  /H47     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HW2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HW3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HW4     
   9998 "Flagged cases"
  /HW5     
   9998 "Flagged cases"
  /HW6     
   99998 "Flagged cases"
  /HW7     
   9998 "Flagged cases"
  /HW8     
   9998 "Flagged cases"
  /HW9     
   99998 "Flagged cases"
  /HW10    
   9998 "Flagged cases"
  /HW11    
   9998 "Flagged cases"
  /HW12    
   99998 "Flagged cases"
  /HW13    
      0 "Measured"
      1 "Dead"
      2 "Sick"
      3 "Not present"
      4 "Refused"
      5 "Mother refused"
      6 "Other"
      7 "No measurement found in household"
  /HW15    
      0 "Not measured"
      1 "Lying"
      2 "Standing"
  /HW16    
     97 "Inconsistent"
     98 "Don't know"
  /HW51    
      0 "Not in household"
  /HW52    
      1 "Granted"
      2 "Refused"
  /HW53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HW55    
      0 "Measured"
      1 "Dead"
      3 "Not present"
      4 "Refused"
      6 "Other"
      7 "No measurement found in household"
  /HW56    
    997 "Inconsistent"
  /HW57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HW58    
      0 "No"
      1 "Yes"
  /HW70    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HW71    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HW72    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HW73    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /ML0     
      0 "No net"
      1 "Only treated nets"
      2 "Both treated and untreated nets"
      3 "Only untreated nets"
  /ML1     
     98 "Don't know"
  /ML2     
      1 "Antenatal visit"
      2 "Another facility visit"
      6 "Other source"
  /ML11    
      0 "No"
      1 "Yes, fever only"
      2 "Yes, cough only"
      3 "Both fever and cough"
      8 "Don't know"
  /ML12    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /ML13A   
      0 "No"
      1 "Yes"
  /ML13B   
      0 "No"
      1 "Yes"
  /ML13C   
      0 "No"
      1 "Yes"
  /ML13D   
      0 "No"
      1 "Yes"
  /ML13E   
      0 "No"
      1 "Yes"
  /ML13F   
      0 "No"
      1 "Yes"
  /ML13G   
      0 "No"
      1 "Yes"
  /ML13H   
      0 "No"
      1 "Yes"
  /ML13I   
      0 "No"
      1 "Yes"
  /ML13J   
      0 "No"
      1 "Yes"
  /ML13K   
      0 "No"
      1 "Yes"
  /ML13L   
      0 "No"
      1 "Yes"
  /ML13M   
      0 "No"
      1 "Yes"
  /ML13N   
      0 "No"
      1 "Yes"
  /ML13O   
      0 "No"
      1 "Yes"
  /ML13P   
      0 "No"
      1 "Yes"
  /ML13X   
      0 "No"
      1 "Yes"
  /ML13Y   
      0 "No"
      1 "Yes, nothing taken"
  /ML13Z   
      0 "No"
      1 "Yes, don't know"
  /ML14A   
      0 "No"
      1 "Yes"
  /ML14B   
      0 "No"
      1 "Yes"
  /ML14Y   
      0 "No"
      1 "Yes"
  /ML14Z   
      0 "No"
      1 "Yes"
  /ML15A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML15B   
      7 "7+ days"
      8 "Don't know"
  /ML15C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML16A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML16B   
      7 "7+ days"
      8 "Don't know"
  /ML16C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML17A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML17B   
      7 "7+ days"
      8 "Don't know"
  /ML17C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML18A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML18B   
      7 "7+ days"
      8 "Don't know"
  /ML18C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML19A   
      0 "No"
      1 "Yes"
  /ML19B   
      0 "No"
      1 "Yes"
  /ML19C   
      0 "No"
      1 "Yes"
  /ML19D   
      0 "No"
      1 "Yes"
  /ML19E   
      0 "No"
      1 "Yes"
  /ML19F   
      0 "No"
      1 "Yes"
  /ML19X   
      0 "No"
      1 "Yes"
  /ML19Y   
      0 "No"
      1 "Yes"
  /ML19Z   
      0 "No"
      1 "Yes"
  /ML20A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML20B   
      7 "7+ days"
      8 "Don't know"
  /ML20C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML21A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML21B   
      7 "7+ days"
      8 "Don't know"
  /ML21C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML22A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML22B   
      7 "7+ days"
      8 "Don't know"
  /ML22C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML23A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML23B   
      7 "7+ days"
      8 "Don't know"
  /ML23C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML24C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /G100    
      0 "No"
      1 "Yes"
  /G101    
      0 "No"
      1 "Yes"
  /G102    
      0 "No"
      1 "Yes"
  /G103    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /G104    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /G105    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /G106    
     95 "During infancy"
     98 "Don't know"
  /G107    
     10 "HEALTH PROFESSIONAL"
     11 "Doctor"
     12 "Trained nurse/midwife"
     16 "Other health professional"
     20 "TRADITIONAL"
     21 'Traditional "circumciser"'
     22 "Traditional birth attendant"
     26 "Other traditional"
     98 "Don't know"
  /G108    
     95 "No daughter circumcised"
  /G110    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /G111    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /G112    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /G113    
     95 "During infancy"
     98 "Don't know"
  /G114    
     10 "HEALTH PROFESSIONAL"
     11 "Doctor"
     12 "Trained nurse/midwife"
     16 "Other health professional"
     20 "TRADITIONAL"
     21 'Traditional "circumciser"'
     22 "Traditional birth attendant"
     26 "Other traditional"
     98 "Don't know"
  /G115    
      0 "No: all circumcised"
      1 "Yes"
      8 "Don't know"
  /G116    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /G117A   
      0 "No"
      1 "Yes"
  /G117B   
      0 "No"
      1 "Yes"
  /G117C   
      0 "No"
      1 "Yes"
  /G117D   
      0 "No"
      1 "Yes"
  /G117E   
      0 "No"
      1 "Yes"
  /G117F   
      0 "No"
      1 "Yes"
  /G117G   
      0 "No"
      1 "Yes"
  /G117H   
      0 "No"
      1 "Yes"
  /G117I   
      0 "No"
      1 "Yes"
  /G117J   
      0 "No"
      1 "Yes: No opinion/Don't know"
  /G117X   
      0 "No"
      1 "Yes"
  /G117Y   
      0 "No"
      1 "Yes"
  /G118    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /G119    
      1 "Continued"
      2 "Stopped"
      3 "Depends"
      8 "Don't know"
  /SZONE   
      1 "Desert"
      2 "Central"
      3 "Coast"
  /SHREG   
      1 "Central"
      2 "Periphery"
      3 "Outlying"
  /S426    
      1 "Antenatal visit"
      2 "Another facility visit"
      3 "Traditional birth attend"
      6 "Other source"
  /SYF     
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /SYFD    
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SYFM    
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SYFY    
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
  /SPC1    
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /SPC1D   
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SPC1M   
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SPC1Y   
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
  /SPC2    
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /SPC2D   
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SPC2M   
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SPC2Y   
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
  /SPC3    
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /SPC3D   
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SPC3M   
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SPC3Y   
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
  /SHP0    
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /SHB0D   
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SHB0M   
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
  /SHB0Y   
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\ZZ62\ZZBR62FL.sav'.
